// Generates src/legacy/index.js from build.py's two manifests, so the one
// entry point cannot drift from the order the concatenated page had.
//
//   node scripts/legacy-index.mjs [--write]
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const UIWEB = join(dirname(fileURLToPath(import.meta.url)), '..')
const py = readFileSync(join(UIWEB, 'build.py'), 'utf8')
const manifest = (n) => [...py.match(new RegExp(`_${n}_PARTS = \\[([\\s\\S]*?)\\]`))[1].matchAll(/"([^"]+)"/g)].map((x) => x[1])

const ident = (dir, file) => dir + file.replace(/\.js$/, '').replace(/^(\d+)-(.*)$/, (_, n, rest) => n + rest.replace(/-(.)/g, (__, c) => c.toUpperCase()))
const layer = (dir, parts) => parts.map((p) => ({ id: ident(dir, p), path: `./${dir}/${p}` }))

const demo = layer('demo', manifest('DEMO'))
const live = layer('live', manifest('LIVE'))
const all = [...demo, ...live]

const out = `/* The one entry point of what is left of the legacy page script.

   The 48 parts were concatenated in the order the two manifests in
   ui-web/build.py pin, and that order was load-bearing: a part read names the
   parts before it had already defined. ES modules do not honour that order --
   each module evaluates when the graph first reaches it, depth first -- so the
   order was taken out of the evaluation and put here instead: every module body
   is now inert declarations, and everything that used to happen while the
   script ran happens in its install(), called from this list in the manifests'
   order.

   What installs from here is chrome: the panels, the dialogs and the shortcut
   table that stage C turns into components. The page's data wiring and its boot
   are src/state/{install,boot}.ts, called by src/main.tsx right after this.

   Generated by ui-web/scripts/legacy-index.mjs; run it after changing a
   manifest. */

${all.map((m) => `import * as ${m.id} from '${m.path}'`).join('\n')}
const DEMO = [
${demo.map((m) => `  ${m.id},`).join('\n')}
]

const LIVE = [
${live.map((m) => `  ${m.id},`).join('\n')}
]

export function installLegacy() {
  for (const part of DEMO) part.install()
  for (const part of LIVE) part.install()
}
`
if (process.argv.includes('--write')) {
  writeFileSync(join(UIWEB, 'src', 'legacy', 'index.js'), out)
  console.log(`wrote src/legacy/index.js (${all.length} modules)`)
} else {
  process.stdout.write(out)
}
