site_name: Raven
site_url: https://evermind-ai.github.io/Raven/
repo_url: https://github.com/EverMind-AI/Raven
docs_dir: docs

theme:
  name: material
  features:
    - navigation.sections
    - content.code.copy
  palette:
    - scheme: default
      primary: black
      accent: amber

markdown_extensions:
  - admonition
  - tables
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.highlight

plugins:
  - search
  - i18n:
      docs_structure: suffix
      fallback_to_default: true
      reconfigure_material: true
      reconfigure_search: true
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: zh
          name: 简体中文
          build: true

nav:
  - Home: index.md
