/* The one entry point of the legacy page script.

   Until this refactor the 48 parts were concatenated in the order the two
   manifests in ui-web/build.py pin, and that order was load-bearing: a part
   read names the parts before it had already defined. ES modules do not
   honour that order -- each module evaluates when the graph first reaches it,
   depth first -- so the order was taken out of the evaluation and put here
   instead: every module body is now inert declarations, and everything that
   used to happen while the script ran happens in its install(), called from
   this list in the manifests' order.

   The live half runs only under liveMode(), which is the `return` the live
   layer used to open with: opened from disk or with ?stub=1 the demo shell
   keeps its fixture data.

   Generated by ui-web/scripts/legacy-index.mjs; run it after changing a
   manifest. */

import * as demo010kernel from './demo/010-kernel.js'
import * as demo020prose from './demo/020-prose.js'
import * as demo030fixtures from './demo/030-fixtures.js'
import * as demo040state from './demo/040-state.js'
import * as demo050rail from './demo/050-rail.js'
import * as demo060conversation from './demo/060-conversation.js'
import * as demo070transcript from './demo/070-transcript.js'
import * as demo080replay from './demo/080-replay.js'
import * as demo090composer from './demo/090-composer.js'
import * as demo100workspace from './demo/100-workspace.js'
import * as demo110subagents from './demo/110-subagents.js'
import * as demo112browser from './demo/112-browser.js'
import * as demo120capabilities from './demo/120-capabilities.js'
import * as demo130settings from './demo/130-settings.js'
import * as demo140schedule from './demo/140-schedule.js'
import * as demo145connections from './demo/145-connections.js'
import * as demo150chrome from './demo/150-chrome.js'
import * as demo152skills from './demo/152-skills.js'
import * as demo153plugins from './demo/153-plugins.js'
import * as demo154playbooks from './demo/154-playbooks.js'
import * as demo155bridge from './demo/155-bridge.js'
import * as demo160boot from './demo/160-boot.js'
import * as live010bootGuard from './live/010-boot-guard.js'
import * as live020rpc from './live/020-rpc.js'
import * as live030sessions from './live/030-sessions.js'
import * as live040history from './live/040-history.js'
import * as live050turn from './live/050-turn.js'
import * as live060parked from './live/060-parked.js'
import * as live070notify from './live/070-notify.js'
import * as live080overrides from './live/080-overrides.js'
import * as live090extensions from './live/090-extensions.js'
import * as live100schedules from './live/100-schedules.js'
import * as live110connections from './live/110-connections.js'
import * as live120settings from './live/120-settings.js'
import * as live130writes from './live/130-writes.js'
import * as live140skills from './live/140-skills.js'
import * as live150plugins from './live/150-plugins.js'
import * as live160memory from './live/160-memory.js'
import * as live165knowledge from './live/165-knowledge.js'
import * as live167playbooks from './live/167-playbooks.js'
import * as live170workspace from './live/170-workspace.js'
import * as live180attachments from './live/180-attachments.js'
import * as live190sessionActions from './live/190-session-actions.js'
import * as live200boot from './live/200-boot.js'
import * as live210updateNotice from './live/210-update-notice.js'
import * as live220browser from './live/220-browser.js'
import * as live230tabs from './live/230-tabs.js'
import * as live240externalAgents from './live/240-external-agents.js'
import { liveMode } from './live/010-boot-guard.js'

const DEMO = [
  demo010kernel,
  demo020prose,
  demo030fixtures,
  demo040state,
  demo050rail,
  demo060conversation,
  demo070transcript,
  demo080replay,
  demo090composer,
  demo100workspace,
  demo110subagents,
  demo112browser,
  demo120capabilities,
  demo130settings,
  demo140schedule,
  demo145connections,
  demo150chrome,
  demo152skills,
  demo153plugins,
  demo154playbooks,
  demo155bridge,
  demo160boot,
]

const LIVE = [
  live010bootGuard,
  live020rpc,
  live030sessions,
  live040history,
  live050turn,
  live060parked,
  live070notify,
  live080overrides,
  live090extensions,
  live100schedules,
  live110connections,
  live120settings,
  live130writes,
  live140skills,
  live150plugins,
  live160memory,
  live165knowledge,
  live167playbooks,
  live170workspace,
  live180attachments,
  live190sessionActions,
  live200boot,
  live210updateNotice,
  live220browser,
  live230tabs,
  live240externalAgents,
]

export function installLegacy() {
  for (const part of DEMO) part.install()
  if (!liveMode()) return
  for (const part of LIVE) part.install()
}
