/* The one entry point of what is left of the legacy page script.

   The 48 parts were concatenated in the order the two manifests in
   ui-web/build.py pin, and that order was load-bearing: a part read names the
   parts before it had already defined. ES modules do not honour that order --
   each module evaluates when the graph first reaches it, depth first -- so the
   order was taken out of the evaluation and put here instead: every module body
   is now inert declarations, and everything that used to happen while the
   script ran happens in its install(), called from this list in the manifests'
   order.

   What installs from here is chrome: the panels, the dialogs and the shortcut
   table that stage C turns into components. The page's data wiring and its boot
   are src/state/{install,boot}.ts, called by src/main.tsx right after this.

   Generated by ui-web/scripts/legacy-index.mjs; run it after changing a
   manifest. */

import * as demo010kernel from './demo/010-kernel.js'
import * as demo040state from './demo/040-state.js'
import * as demo050rail from './demo/050-rail.js'
import * as demo060conversation from './demo/060-conversation.js'
import * as demo070transcript from './demo/070-transcript.js'
import * as demo090composer from './demo/090-composer.js'
import * as demo100workspace from './demo/100-workspace.js'
import * as demo120capabilities from './demo/120-capabilities.js'
import * as demo130settings from './demo/130-settings.js'
import * as demo140schedule from './demo/140-schedule.js'
import * as demo145connections from './demo/145-connections.js'
import * as demo150chrome from './demo/150-chrome.js'
import * as demo152skills from './demo/152-skills.js'
import * as demo153plugins from './demo/153-plugins.js'
import * as demo154playbooks from './demo/154-playbooks.js'
import * as demo155bridge from './demo/155-bridge.js'
import * as demo160boot from './demo/160-boot.js'
import * as live120settings from './live/120-settings.js'
const DEMO = [
  demo010kernel,
  demo040state,
  demo050rail,
  demo060conversation,
  demo070transcript,
  demo090composer,
  demo100workspace,
  demo120capabilities,
  demo130settings,
  demo140schedule,
  demo145connections,
  demo150chrome,
  demo152skills,
  demo153plugins,
  demo154playbooks,
  demo155bridge,
  demo160boot,
]

const LIVE = [
  live120settings,
]

export function installLegacy() {
  for (const part of DEMO) part.install()
  for (const part of LIVE) part.install()
}
