"""Multimodal generation tools (OpenRouter backend).

OpenRouter exposes generation through the OpenAI-compatible chat-completions
API with extra *output modalities* — there are no standalone
``/images/generations`` or ``/audio/speech`` endpoints. Both tools here POST
to ``{base}/chat/completions`` with a ``modalities`` array and read the
generated bytes back from the assistant message:

- ``image_generate``  → ``modalities:["image","text"]`` → ``message.images[].image_url.url``
  (a ``data:image/...;base64,...`` URI). Default model **Nano Banana**
  (``google/gemini-2.5-flash-image``).
- ``text_to_speech``  → ``modalities:["audio","text"]`` + ``audio:{voice,format}``.
  OpenRouter only returns audio when ``stream:true`` AND only as raw ``pcm16``
  in that mode, so we stream, concatenate the base64 ``delta.audio.data`` chunks,
  and wrap the PCM (24 kHz / mono / 16-bit) into a WAV with the stdlib ``wave``
  module — zero binary dependency. mp3/opus/flac are transcoded from that WAV
  only when ``ffmpeg`` is on PATH; otherwise we keep the WAV and say so.
  Default model ``openai/gpt-audio-mini``.

Video uses a separate async endpoint (NOT chat-completions):

- ``video_generate``  → ``POST {base}/videos`` with ``{model, prompt}`` → ``202``
  ``{id, polling_url, status}`` → poll ``polling_url`` until ``completed`` (URLs
  to download) or ``failed`` (with ``error``). Default model
  ``kwaivgi/kling-v3.0-std`` (Kling v3 Standard). Requires postpaid billing /
  credits enabled on the OpenRouter account.

Music uses the MiniMax REST API (also not chat-completions):

- ``music_generate``  → ``POST {base}/music_generation`` with
  ``{model, prompt, lyrics, output_format, ...}`` → ``base_resp.status_code``
  ``0`` on success, ``data.status`` ``2`` when the track is ready, and
  ``data.audio`` as either a hex-encoded payload (``output_format:"hex"``) or
  a list of downloadable URLs (``output_format:"url"``). Default model
  ``music-3.0``; cover models ``music-cover`` / ``music-cover-free`` take a
  reference track via ``audio_url`` / ``audio_base64``.

Generated files are written under ``<workspace>/<output_subdir>`` and the path
is returned so the agent can forward it with the ``message`` tool's ``media``
field. A denied request (HTTP 403) hints at setting ``tools.media.proxy``.

See demos/skill_retrieval/skills/image-gen/SKILL.md for the image recipe.
"""

from __future__ import annotations

import asyncio
import base64
import json
import os
import shutil
import uuid
import wave
from pathlib import Path
from typing import TYPE_CHECKING, Any

import httpx
from loguru import logger

from raven.agent.tools.base import Tool
from raven.utils.helpers import image_block

if TYPE_CHECKING:
    from raven.config.schema import MediaToolConfig

_DEFAULT_BASE = "https://openrouter.ai/api/v1"

_EXT_MIME = {
    ".png": "image/png",
    ".jpg": "image/jpeg",
    ".jpeg": "image/jpeg",
    ".webp": "image/webp",
    ".gif": "image/gif",
    ".bmp": "image/bmp",
}


class _OpenRouterMediaTool(Tool):
    """Shared base: config/env resolution, chat-completions call, file output."""

    default_model = ""

    def __init__(
        self,
        config: "MediaToolConfig | None" = None,
        *,
        workspace: Path | None = None,
        proxy: str | None = None,
        output_subdir: str = "generated",
    ):
        self._config = config
        self._workspace = Path(workspace) if workspace else Path.cwd()
        self._proxy = proxy
        self._output_subdir = output_subdir

    # ── config resolution (at call time, so env/config edits are picked up) ──

    @staticmethod
    def _resolve_key(config: "MediaToolConfig | None") -> str:
        """The credential chain in one place: this tool's section, then the
        shared environment variable.

        A static method so :meth:`has_key` can ask it without an instance --
        this base is abstract, and the callers deciding whether a capability
        works hold a config and no tool.
        """
        cfg_key = getattr(config, "api_key", "") if config else ""
        return cfg_key or os.environ.get("OPENROUTER_API_KEY", "")

    @property
    def api_key(self) -> str:
        return self._resolve_key(self._config)

    @classmethod
    def is_configured(cls, config: "MediaToolConfig | None") -> bool:
        """Whether this deployment asked for the tool at all.

        A model *or* a key, matching what ``AgentLoop`` registers on: the key
        alone would let an OpenRouter credential set for chat quietly switch on
        three tools that bill per call, and the model alone would miss the
        deployment that names no model and relies on ``default_model``.

        A classmethod because the caller deciding whether to offer the tool has
        a config and no instance, and because the answer has to be askable
        without building one.
        """
        if config is None:
            return False
        return bool(config.api_key or config.model)

    @classmethod
    def has_key(cls, config: "MediaToolConfig | None") -> bool:
        """Whether a credential resolves for this tool.

        A different question from :meth:`is_configured`, which answers whether
        the deployment asked for the tool at all: a section naming only a model
        is registered and offered to the model, and then every call returns
        :meth:`_no_key_error`. Asked of the tool because only the tool consults
        both the section and ``OPENROUTER_API_KEY``, so a caller reading the
        config alone answers wrong for every deployment that exports it.
        """
        return bool(cls._resolve_key(config))

    @property
    def api_base(self) -> str:
        cfg_base = getattr(self._config, "api_base", "") if self._config else ""
        return (cfg_base or _DEFAULT_BASE).rstrip("/")

    def _model(self, override: str | None) -> str:
        cfg_model = getattr(self._config, "model", "") if self._config else ""
        return override or cfg_model or self.default_model

    def _output_path(self, ext: str) -> Path:
        out_dir = self._workspace / self._output_subdir
        out_dir.mkdir(parents=True, exist_ok=True)
        return out_dir / f"{self.name}-{uuid.uuid4().hex[:12]}.{ext}"

    def _no_key_error(self) -> str:
        return json.dumps(
            {
                "error": (
                    f"{self.name}: no API key configured. Set it in "
                    f"~/.raven/config.json under tools.media.*.apiKey, "
                    f"providers.openrouter.apiKey, or export OPENROUTER_API_KEY, "
                    f"then restart the gateway."
                )
            },
            ensure_ascii=False,
        )

    async def _chat(self, payload: dict[str, Any]) -> dict[str, Any]:
        """POST to chat/completions and return the assistant message dict.

        Raises ``httpx.HTTPStatusError`` on non-2xx so callers can format it.
        """
        async with httpx.AsyncClient(proxy=self._proxy, timeout=180.0) as client:
            r = await client.post(
                f"{self.api_base}/chat/completions",
                headers={"Authorization": f"Bearer {self.api_key}", "Content-Type": "application/json"},
                json=payload,
            )
            r.raise_for_status()
            data = r.json()
        return (data.get("choices") or [{}])[0].get("message") or {}

    def _format_http_error(self, e: httpx.HTTPStatusError) -> str:
        body = e.response.text[:400]
        hint = ""
        if e.response.status_code == 403:
            hint = (
                " | Request denied (HTTP 403). You can route media calls through a "
                "proxy via tools.media.proxy (or HTTPS_PROXY) and retry."
            )
        logger.error("{} HTTP {}: {}", self.name, e.response.status_code, body)
        return json.dumps({"error": f"HTTP {e.response.status_code}: {body}{hint}"}, ensure_ascii=False)


class ImageGenerateTool(_OpenRouterMediaTool):
    """Generate (or edit) an image from a text prompt via Nano Banana on OpenRouter."""

    name = "image_generate"
    default_model = "google/gemini-2.5-flash-image"  # Nano Banana
    description = (
        "Generate an image from a text prompt (optionally editing/varying input "
        "images). Saves the image under the workspace and returns its file path; "
        "forward it to the user with the `message` tool's `media` field."
    )
    parameters = {
        "type": "object",
        "properties": {
            "prompt": {"type": "string", "description": "Text description of the image to create"},
            "model": {
                "type": "string",
                "description": (
                    "Optional OpenRouter image model override, e.g. "
                    "'google/gemini-2.5-flash-image' (Nano Banana) or "
                    "'google/gemini-3.1-flash-image-preview' (Nano Banana 2)"
                ),
            },
            "images": {
                "type": "array",
                "items": {"type": "string"},
                "description": (
                    "Optional input images to edit/vary: local file paths, http(s) URLs, or data: URIs (max 6)"
                ),
            },
        },
        "required": ["prompt"],
    }

    def _image_part(self, ref: str) -> dict[str, Any]:
        """Build an OpenAI-style image_url content part from a path/URL/data URI."""
        if ref.startswith(("http://", "https://", "data:")):
            return image_block(ref)
        path = Path(ref).expanduser()
        data = path.read_bytes()
        mime = _EXT_MIME.get(path.suffix.lower(), "image/png")
        b64 = base64.b64encode(data).decode("ascii")
        return image_block(f"data:{mime};base64,{b64}")

    async def execute(
        self,
        prompt: str,
        model: str | None = None,
        images: list[str] | None = None,
        **kwargs: Any,
    ) -> str:
        if not self.api_key:
            return self._no_key_error()

        model_id = self._model(model)
        if images:
            content: Any = [{"type": "text", "text": prompt}]
            try:
                for ref in images[:6]:
                    content.append(self._image_part(ref))
            except OSError as e:
                return json.dumps({"error": f"could not read input image: {e}"}, ensure_ascii=False)
        else:
            content = prompt

        payload = {
            "model": model_id,
            "messages": [{"role": "user", "content": content}],
            "modalities": ["image", "text"],
        }

        try:
            msg = await self._chat(payload)
        except httpx.HTTPStatusError as e:
            return self._format_http_error(e)
        except Exception as e:
            logger.error("image_generate error: {}", e)
            return json.dumps({"error": str(e)}, ensure_ascii=False)

        out_images = msg.get("images") or []
        if not out_images:
            note = msg.get("content") or msg.get("refusal") or ""
            return json.dumps(
                {"error": "no image returned", "model": model_id, "note": note[:300]},
                ensure_ascii=False,
            )

        paths: list[str] = []
        for item in out_images:
            url = (item.get("image_url") or {}).get("url", "")
            if not url.startswith("data:"):
                continue
            b64 = url.split(",", 1)[1]
            path = self._output_path("png")
            path.write_bytes(base64.b64decode(b64))
            paths.append(str(path))

        if not paths:
            return json.dumps({"error": "image payload was not a data URI", "model": model_id}, ensure_ascii=False)

        logger.info("image_generate: {} image(s) via {} -> {}", len(paths), model_id, paths)
        return json.dumps({"success": True, "model": model_id, "paths": paths}, ensure_ascii=False)


class SpeechGenerateTool(_OpenRouterMediaTool):
    """Synthesize speech from text via an OpenRouter audio model (gpt-audio)."""

    name = "text_to_speech"
    default_model = "openai/gpt-audio-mini"
    description = (
        "Synthesize speech audio from text. Saves an audio file under the "
        "workspace and returns its path; forward it with the `message` tool's "
        "`media` field."
    )
    parameters = {
        "type": "object",
        "properties": {
            "text": {"type": "string", "description": "Text to speak"},
            "voice": {
                "type": "string",
                "description": "Voice name (e.g. alloy, echo, fable, onyx, nova, shimmer)",
                "default": "alloy",
            },
            "format": {
                "type": "string",
                "enum": ["wav", "mp3", "opus", "flac"],
                "default": "wav",
                "description": (
                    "Output container. 'wav' is always available (zero deps); "
                    "mp3/opus/flac require ffmpeg on PATH and fall back to wav if absent."
                ),
            },
            "model": {
                "type": "string",
                "description": "Optional OpenRouter audio model override (e.g. openai/gpt-audio)",
            },
        },
        "required": ["text"],
    }

    # OpenRouter streams audio as raw pcm16; OpenAI's gpt-audio emits it at
    # 24 kHz, mono, 16-bit — the params needed to wrap it into a valid WAV.
    _PCM_RATE = 24_000
    _PCM_CHANNELS = 1
    _PCM_SAMPWIDTH = 2

    async def execute(
        self,
        text: str,
        voice: str = "alloy",
        format: str = "wav",
        model: str | None = None,
        **kwargs: Any,
    ) -> str:
        if not self.api_key:
            return self._no_key_error()

        model_id = self._model(model)
        payload = {
            "model": model_id,
            # Instruct verbatim narration — gpt-audio is conversational, so an
            # explicit directive keeps it from ad-libbing a reply.
            "messages": [
                {
                    "role": "user",
                    "content": f"Read the following text aloud verbatim, adding nothing:\n\n{text}",
                }
            ],
            "modalities": ["audio", "text"],
            # OpenRouter rejects audio output unless stream=true, and in stream
            # mode only the raw pcm16 format is accepted — we wrap/transcode after.
            "stream": True,
            "audio": {"voice": voice, "format": "pcm16"},
        }

        try:
            pcm, transcript = await self._stream_audio_pcm(payload)
        except httpx.HTTPStatusError as e:
            return self._format_http_error(e)
        except Exception as e:
            logger.error("text_to_speech error: {}", e)
            return json.dumps({"error": str(e)}, ensure_ascii=False)

        if not pcm:
            return json.dumps(
                {"error": "no audio returned", "model": model_id, "note": transcript[:300]},
                ensure_ascii=False,
            )

        wav_path = self._output_path("wav")
        self._write_wav(wav_path, pcm)
        out_path, out_fmt, note = await self._maybe_transcode(wav_path, format)

        logger.info("text_to_speech: via {} -> {}", model_id, out_path)
        result: dict[str, Any] = {
            "success": True,
            "model": model_id,
            "path": str(out_path),
            "format": out_fmt,
        }
        if transcript:
            result["transcript"] = transcript
        if note:
            result["note"] = note
        return json.dumps(result, ensure_ascii=False)

    async def _stream_audio_pcm(self, payload: dict[str, Any]) -> tuple[bytes, str]:
        """Stream a chat-completions audio response → (pcm16 bytes, transcript).

        Concatenates the base64 ``delta.audio.data`` chunks (and any transcript
        text) from the SSE stream. Raises ``httpx.HTTPStatusError`` on non-2xx so
        ``execute`` can format it the same way as the image path.
        """
        pcm = bytearray()
        transcript_parts: list[str] = []
        headers = {
            "Authorization": f"Bearer {self.api_key}",
            "Content-Type": "application/json",
        }
        async with httpx.AsyncClient(proxy=self._proxy, timeout=180.0) as client:
            async with client.stream("POST", f"{self.api_base}/chat/completions", headers=headers, json=payload) as r:
                if r.status_code >= 400:
                    await r.aread()  # load body so .text/raise_for_status carry the error
                    r.raise_for_status()
                async for line in r.aiter_lines():
                    if not line.startswith("data:"):
                        continue
                    data = line[len("data:") :].strip()
                    if data == "[DONE]":
                        break
                    try:
                        obj = json.loads(data)
                    except json.JSONDecodeError:
                        continue
                    delta = (obj.get("choices") or [{}])[0].get("delta") or {}
                    audio = delta.get("audio") or {}
                    if chunk := audio.get("data"):
                        pcm += base64.b64decode(chunk)
                    if t := audio.get("transcript"):
                        transcript_parts.append(t)
        return bytes(pcm), "".join(transcript_parts)

    def _write_wav(self, path: Path, pcm: bytes) -> None:
        """Wrap raw pcm16 bytes into a WAV container (stdlib, no deps)."""
        with wave.open(str(path), "wb") as w:
            w.setnchannels(self._PCM_CHANNELS)
            w.setsampwidth(self._PCM_SAMPWIDTH)
            w.setframerate(self._PCM_RATE)
            w.writeframes(pcm)

    async def _maybe_transcode(self, wav_path: Path, fmt: str) -> tuple[Path, str, str]:
        """Transcode the WAV to ``fmt`` via ffmpeg. Returns (path, format, note).

        wav needs nothing; other formats need ffmpeg and fall back to wav with a
        note when it is missing or the conversion fails.
        """
        if fmt == "wav":
            return wav_path, "wav", ""
        ffmpeg = shutil.which("ffmpeg")
        if not ffmpeg:
            return wav_path, "wav", f"ffmpeg not on PATH; saved as wav instead of {fmt}"
        out = wav_path.with_suffix(f".{fmt}")
        proc = await asyncio.create_subprocess_exec(
            ffmpeg,
            "-y",
            "-i",
            str(wav_path),
            str(out),
            stdout=asyncio.subprocess.DEVNULL,
            stderr=asyncio.subprocess.PIPE,
        )
        _, err = await proc.communicate()
        if proc.returncode != 0 or not out.exists():
            logger.warning("ffmpeg transcode to {} failed: {}", fmt, err.decode("utf-8", "replace")[:200])
            return wav_path, "wav", f"ffmpeg transcode to {fmt} failed; saved as wav"
        wav_path.unlink(missing_ok=True)
        return out, fmt, ""


def _find_video_url(obj: Any) -> str | None:
    """Recursively find the first downloadable video URL / data URI in a response.

    The exact completed-response shape for OpenRouter's /videos endpoint is not
    publicly pinned down, so we search defensively rather than hard-code a path.
    """
    if isinstance(obj, str):
        s = obj
        if s.startswith("data:video") or (
            s.startswith(("http://", "https://"))
            and any(ext in s.lower() for ext in (".mp4", ".webm", ".mov", "video"))
        ):
            return s
        return None
    if isinstance(obj, dict):
        # Prefer obvious keys first.
        for key in ("url", "video_url", "download_url", "video", "output", "result"):
            if key in obj and (found := _find_video_url(obj[key])):
                return found
        for v in obj.values():
            if found := _find_video_url(v):
                return found
        return None
    if isinstance(obj, list):
        for item in obj:
            if found := _find_video_url(item):
                return found
        return None
    return None


def _pick_video_url(status: dict[str, Any]) -> str | None:
    """Choose the downloadable content URL from a completed /videos response.

    OpenRouter's completed shape exposes the rendered video under
    ``signed_urls`` / ``unsigned_urls`` (lists). We prefer those explicitly:
    the job's own ``polling_url`` also lives under ``/videos/`` and would
    otherwise be matched by ``_find_video_url``'s "video" substring heuristic,
    yielding the status JSON instead of the clip. For any other (undocumented)
    provider shape we fall back to a defensive scan that excludes the
    polling/status URL.
    """
    for key in ("signed_urls", "unsigned_urls"):
        urls = status.get(key)
        if isinstance(urls, list) and urls and isinstance(urls[0], str):
            return urls[0]
    scannable = {k: v for k, v in status.items() if k != "polling_url"}
    return _find_video_url(scannable)


class VideoGenerateTool(_OpenRouterMediaTool):
    """Generate a video from a text prompt via Kling on OpenRouter (async)."""

    name = "video_generate"
    default_model = "kwaivgi/kling-v3.0-std"  # Kling v3 Standard
    description = (
        "Generate a short video from a text prompt (async; takes a while). Saves "
        "the video under the workspace and returns its path; forward it with the "
        "`message` tool's `media` field."
    )
    parameters = {
        "type": "object",
        "properties": {
            "prompt": {"type": "string", "description": "Text description of the video"},
            "model": {
                "type": "string",
                "description": "Optional OpenRouter video model override (default kwaivgi/kling-v3.0-std)",
            },
            "params": {
                "type": "object",
                "description": (
                    "Optional extra provider params merged into the request, e.g. "
                    '{"duration": 5, "aspect_ratio": "16:9"} (3-15s; 16:9/9:16/1:1)'
                ),
            },
        },
        "required": ["prompt"],
    }

    _POLL_INTERVAL_S = 6.0
    _POLL_TIMEOUT_S = 600.0
    # Backstop above the 600s polling cap; the poll loop gives up first.
    timeout_seconds = 660.0

    async def execute(
        self,
        prompt: str,
        model: str | None = None,
        params: dict[str, Any] | None = None,
        **kwargs: Any,
    ) -> str:
        if not self.api_key:
            return self._no_key_error()

        model_id = self._model(model)
        body: dict[str, Any] = {"model": model_id, "prompt": prompt}
        if params:
            body.update(params)

        headers = {"Authorization": f"Bearer {self.api_key}", "Content-Type": "application/json"}
        try:
            async with httpx.AsyncClient(proxy=self._proxy, timeout=120.0) as client:
                # 1) submit job
                r = await client.post(f"{self.api_base}/videos", headers=headers, json=body)
                r.raise_for_status()
                job = r.json()
                poll_url = job.get("polling_url") or f"{self.api_base}/videos/{job.get('id')}"

                # 2) poll
                status = await self._poll(client, poll_url, headers)
                state = status.get("status")
                if state != "completed":
                    return json.dumps(
                        {
                            "error": f"video job status={state}",
                            "detail": status.get("error") or status,
                            "model": model_id,
                        },
                        ensure_ascii=False,
                    )

                # 3) locate + download the video
                video_url = _pick_video_url(status)
                if not video_url:
                    return json.dumps(
                        {"error": "completed but no video URL found", "raw": status},
                        ensure_ascii=False,
                    )
                if video_url.startswith("data:"):
                    data = base64.b64decode(video_url.split(",", 1)[1])
                else:
                    # OpenRouter returns "unsigned" content URLs on its own host
                    # that need the same Authorization header as the API. Only
                    # send it to OpenRouter — never leak the key to a third-party
                    # (pre-signed CDN/S3) host.
                    dl_headers = headers if video_url.startswith(self.api_base) else None
                    dl = await client.get(video_url, headers=dl_headers, timeout=180.0)
                    dl.raise_for_status()
                    data = dl.content
        except httpx.HTTPStatusError as e:
            return self._format_http_error(e)
        except Exception as e:
            logger.error("video_generate error: {}", e)
            return json.dumps({"error": str(e)}, ensure_ascii=False)

        path = self._output_path("mp4")
        path.write_bytes(data)
        logger.info("video_generate: {} bytes via {} -> {}", len(data), model_id, path)
        return json.dumps({"success": True, "model": model_id, "path": str(path)}, ensure_ascii=False)

    async def _poll(self, client: httpx.AsyncClient, poll_url: str, headers: dict[str, str]) -> dict[str, Any]:
        """Poll until the job leaves the pending/processing state or times out."""
        waited = 0.0
        while waited < self._POLL_TIMEOUT_S:
            r = await client.get(poll_url, headers=headers)
            r.raise_for_status()
            job = r.json()
            if job.get("status") not in ("pending", "processing", "queued", "in_progress"):
                return job
            await asyncio.sleep(self._POLL_INTERVAL_S)
            waited += self._POLL_INTERVAL_S
        return {"status": "timeout"}


_MUSIC_DEFAULT_BASE = "https://api.minimax.io/v1"
_MUSIC_AUDIO_FORMATS = ("mp3", "wav", "pcm")


class MusicGenerateTool(Tool):
    """Generate music or a cover via MiniMax's ``/music_generation`` endpoint.

    MiniMax is a dedicated REST API, not chat-completions: one synchronous POST
    returns the finished track. Success is ``base_resp.status_code == 0``;
    ``data.status`` is ``2`` when the track is ready. ``data.audio`` carries the
    result as a hex-encoded payload (``output_format:"hex"``, the only form
    ``stream`` accepts) or a list of downloadable URLs (``output_format:"url"``,
    which expire after 24h so the tool downloads them immediately). Cover models
    (``music-cover`` / ``music-cover-free``) take a reference track through
    ``audio_url`` / ``audio_base64``.
    """

    name = "music_generate"
    default_model = "music-3.0"
    description = (
        "Generate music (or a cover of a reference track) from a text prompt. "
        "Saves the audio under the workspace and returns its path; forward it "
        "to the user with the `message` tool's `media` field."
    )
    timeout_seconds = 600.0

    def __init__(
        self,
        config: "MediaToolConfig | None" = None,
        *,
        workspace: Path | None = None,
        proxy: str | None = None,
        output_subdir: str = "generated",
    ):
        self._config = config
        self._workspace = Path(workspace) if workspace else Path.cwd()
        self._proxy = proxy
        self._output_subdir = output_subdir

    @property
    def api_key(self) -> str:
        cfg_key = getattr(self._config, "api_key", "") if self._config else ""
        return cfg_key or os.environ.get("MINIMAX_API_KEY", "")

    @property
    def api_base(self) -> str:
        cfg_base = getattr(self._config, "api_base", "") if self._config else ""
        return (cfg_base or _MUSIC_DEFAULT_BASE).rstrip("/")

    def _model(self, override: str | None) -> str:
        cfg_model = getattr(self._config, "model", "") if self._config else ""
        return override or cfg_model or self.default_model

    def _output_path(self, ext: str) -> Path:
        out_dir = self._workspace / self._output_subdir
        out_dir.mkdir(parents=True, exist_ok=True)
        return out_dir / f"{self.name}-{uuid.uuid4().hex[:12]}.{ext}"

    def _no_key_error(self) -> str:
        return json.dumps(
            {
                "error": (
                    "music_generate: no API key configured. Set it in "
                    "~/.raven/config.json under tools.media.music.apiKey or "
                    "providers.minimax.apiKey, or export MINIMAX_API_KEY, then "
                    "restart the gateway."
                )
            },
            ensure_ascii=False,
        )

    def _format_http_error(self, e: httpx.HTTPStatusError) -> str:
        body = e.response.text[:400]
        logger.error("{} HTTP {}: {}", self.name, e.response.status_code, body)
        return json.dumps({"error": f"HTTP {e.response.status_code}: {body}"}, ensure_ascii=False)

    parameters = {
        "type": "object",
        "properties": {
            "prompt": {
                "type": "string",
                "description": "Style/mood description of the music to create, or the target cover style",
            },
            "lyrics": {
                "type": "string",
                "description": "Song lyrics, one line per verse, with optional section tags like [Verse]/[Chorus]",
            },
            "model": {
                "type": "string",
                "description": (
                    "Optional MiniMax music model override. Generation: music-3.0 "
                    "(default), music-2.6, music-3.0-free, music-2.6-free. Cover: "
                    "music-cover, music-cover-free."
                ),
            },
            "output_format": {
                "type": "string",
                "enum": ["url", "hex"],
                "default": "url",
                "description": "'url' returns downloadable links (expire in 24h, downloaded here); 'hex' returns the raw audio bytes",
            },
            "audio_setting": {
                "type": "object",
                "description": 'Audio container settings, e.g. {"format": "mp3", "sample_rate": 44100, "bitrate": 256000}',
            },
            "is_instrumental": {"type": "boolean", "description": "Generate instrumental music with no vocals"},
            "lyrics_optimizer": {
                "type": "boolean",
                "description": "Auto-generate lyrics from the prompt when lyrics is empty",
            },
            "stream": {
                "type": "boolean",
                "default": False,
                "description": "Stream the audio; only hex output is supported",
            },
            "audio_url": {
                "type": "string",
                "description": "Reference audio URL (cover models only); local paths are read and base64-encoded",
            },
            "audio_base64": {"type": "string", "description": "Base64-encoded reference audio (cover models only)"},
            "cover_feature_id": {
                "type": "string",
                "description": "Feature id from the music cover preprocess API (cover models only)",
            },
            "aigc_watermark": {
                "type": "integer",
                "description": "Required on the China (api.minimaxi.com) endpoint: 1 embeds an AIGC watermark, 0 does not",
            },
        },
        "required": [],
    }

    async def execute(
        self,
        prompt: str | None = None,
        lyrics: str | None = None,
        model: str | None = None,
        output_format: str = "url",
        audio_setting: dict[str, Any] | None = None,
        is_instrumental: bool | None = None,
        lyrics_optimizer: bool | None = None,
        stream: bool = False,
        audio_url: str | None = None,
        audio_base64: str | None = None,
        cover_feature_id: str | None = None,
        aigc_watermark: int | None = None,
        **kwargs: Any,
    ) -> str:
        if not self.api_key:
            return self._no_key_error()
        if not (prompt or lyrics or audio_url or audio_base64 or cover_feature_id):
            return json.dumps(
                {"error": "music_generate: provide a prompt, lyrics, or a reference audio"},
                ensure_ascii=False,
            )

        model_id = self._model(model)
        payload: dict[str, Any] = {"model": model_id}
        if prompt:
            payload["prompt"] = prompt
        if lyrics:
            payload["lyrics"] = lyrics
        fmt = "hex" if stream else (output_format or "url")
        payload["output_format"] = fmt
        if stream:
            payload["stream"] = True
        if audio_setting:
            payload["audio_setting"] = audio_setting
        if is_instrumental is not None:
            payload["is_instrumental"] = bool(is_instrumental)
        if lyrics_optimizer is not None:
            payload["lyrics_optimizer"] = bool(lyrics_optimizer)
        if cover_feature_id:
            payload["cover_feature_id"] = cover_feature_id
        if aigc_watermark is not None:
            payload["aigc_watermark"] = int(aigc_watermark)
        if audio_url:
            if audio_url.startswith(("http://", "https://", "data:")):
                payload["audio_url"] = audio_url
            else:
                try:
                    payload["audio_base64"] = base64.b64encode(Path(audio_url).expanduser().read_bytes()).decode(
                        "ascii"
                    )
                except OSError as e:
                    return json.dumps({"error": f"could not read reference audio: {e}"}, ensure_ascii=False)
        elif audio_base64:
            payload["audio_base64"] = audio_base64

        headers = {"Authorization": f"Bearer {self.api_key}", "Content-Type": "application/json"}
        try:
            async with httpx.AsyncClient(proxy=self._proxy, timeout=300.0) as client:
                if stream:
                    audio_hex = await self._stream_hex(client, headers, payload)
                    resp = {"data": {"audio": audio_hex, "status": 2}, "base_resp": {"status_code": 0}}
                else:
                    r = await client.post(f"{self.api_base}/music_generation", headers=headers, json=payload)
                    r.raise_for_status()
                    resp = r.json()
                base_resp = resp.get("base_resp") or {}
                if base_resp.get("status_code", 0) != 0:
                    return json.dumps(
                        {
                            "error": base_resp.get("status_msg") or f"status_code={base_resp.get('status_code')}",
                            "model": model_id,
                        },
                        ensure_ascii=False,
                    )
                data = resp.get("data") or {}
                audio = data.get("audio")
                if not audio:
                    status = data.get("status")
                    return json.dumps(
                        {
                            "error": f"music generation status={status}" if status else "no audio returned",
                            "model": model_id,
                        },
                        ensure_ascii=False,
                    )
                if fmt == "url":
                    paths = await self._download_urls(client, audio, audio_setting)
                else:
                    paths = [str(self._save_hex(audio, audio_setting))]
        except httpx.HTTPStatusError as e:
            return self._format_http_error(e)
        except Exception as e:
            logger.error("music_generate error: {}", e)
            return json.dumps({"error": str(e)}, ensure_ascii=False)

        logger.info("music_generate: {} file(s) via {} -> {}", len(paths), model_id, paths)
        return json.dumps({"success": True, "model": model_id, "paths": paths}, ensure_ascii=False)

    async def _stream_hex(self, client: httpx.AsyncClient, headers: dict[str, str], payload: dict[str, Any]) -> str:
        """Concatenate the hex chunks of a streamed music response.

        Each SSE ``data:`` event carries either a JSON object whose ``data.audio``
        is a hex chunk or a bare hex string; ``[DONE]`` ends the stream.
        """
        hex_parts: list[str] = []
        async with client.stream("POST", f"{self.api_base}/music_generation", headers=headers, json=payload) as r:
            if r.status_code >= 400:
                await r.aread()
                r.raise_for_status()
            async for line in r.aiter_lines():
                if not line.startswith("data:"):
                    continue
                data = line[len("data:") :].strip()
                if not data or data == "[DONE]":
                    continue
                try:
                    obj = json.loads(data)
                except json.JSONDecodeError:
                    hex_parts.append(data)
                    continue
                if isinstance(obj, dict):
                    audio = (obj.get("data") or {}).get("audio")
                    if audio:
                        hex_parts.append(audio)
        return "".join(hex_parts)

    async def _download_urls(
        self,
        client: httpx.AsyncClient,
        audio: Any,
        audio_setting: dict[str, Any] | None,
    ) -> list[str]:
        """Download each audio URL (pre-signed, no auth) and save it locally."""
        urls = audio if isinstance(audio, list) else [audio]
        paths: list[str] = []
        for url in urls:
            if not isinstance(url, str) or not url.startswith(("http://", "https://")):
                continue
            r = await client.get(url, timeout=180.0)
            r.raise_for_status()
            path = self._output_path(self._ext_for_url(url, audio_setting))
            path.write_bytes(r.content)
            paths.append(str(path))
        if not paths:
            raise ValueError("no downloadable audio URLs in response")
        return paths

    def _ext_for_url(self, url: str, audio_setting: dict[str, Any] | None) -> str:
        suffix = Path(url.split("?", 1)[0]).suffix.lstrip(".").lower()
        if suffix in _MUSIC_AUDIO_FORMATS:
            return suffix
        fmt = (audio_setting or {}).get("format", "mp3")
        return fmt if fmt in _MUSIC_AUDIO_FORMATS else "mp3"

    def _save_hex(self, audio_hex: str, audio_setting: dict[str, Any] | None) -> Path:
        fmt = (audio_setting or {}).get("format", "mp3")
        fmt = fmt if fmt in _MUSIC_AUDIO_FORMATS else "mp3"
        path = self._output_path(fmt)
        path.write_bytes(bytes.fromhex(audio_hex))
        return path
