"""Multimodal generation tools (OpenRouter backend).

OpenRouter exposes generation through the OpenAI-compatible chat-completions
API with extra *output modalities* — there are no standalone
``/images/generations`` or ``/audio/speech`` endpoints. Both tools here POST
to ``{base}/chat/completions`` with a ``modalities`` array and read the
generated bytes back from the assistant message:

- ``image_generate``  → ``modalities:["image","text"]`` → ``message.images[].image_url.url``
  (a ``data:image/...;base64,...`` URI). Default model **Nano Banana**
  (``google/gemini-2.5-flash-image``).
- ``text_to_speech``  → ``modalities:["audio","text"]`` + ``audio:{voice,format}``.
  OpenRouter only returns audio when ``stream:true`` AND only as raw ``pcm16``
  in that mode, so we stream, concatenate the base64 ``delta.audio.data`` chunks,
  and wrap the PCM (24 kHz / mono / 16-bit) into a WAV with the stdlib ``wave``
  module — zero binary dependency. mp3/opus/flac are transcoded from that WAV
  only when ``ffmpeg`` is on PATH; otherwise we keep the WAV and say so.
  Default model ``openai/gpt-audio-mini``.

Video uses a separate async endpoint (NOT chat-completions):

- ``video_generate``  → ``POST {base}/videos`` with ``{model, prompt}`` → ``202``
  ``{id, polling_url, status}`` → poll ``polling_url`` until ``completed`` (URLs
  to download) or ``failed`` (with ``error``). Default model
  ``kwaivgi/kling-v3.0-std`` (Kling v3 Standard). Requires postpaid billing /
  credits enabled on the OpenRouter account.

Generated files are written under ``<workspace>/<output_subdir>`` and the path
is returned so the agent can forward it with the ``message`` tool's ``media``
field. A denied request (HTTP 403) hints at setting ``tools.media.proxy``.

See demos/skill_retrieval/skills/image-gen/SKILL.md for the image recipe.
"""

from __future__ import annotations

import asyncio
import base64
import json
import os
import shutil
import uuid
import wave
from pathlib import Path
from typing import TYPE_CHECKING, Any

import httpx
from loguru import logger

from raven.agent.tools.base import Tool
from raven.utils.helpers import image_block

if TYPE_CHECKING:
    from raven.config.schema import MediaToolConfig

_DEFAULT_BASE = "https://openrouter.ai/api/v1"
_MINIMAX_VOICE_CLONE_ENDPOINTS = {
    "global_en": "https://api.minimax.io/v1/voice_clone",
    "cn_zh": "https://api.minimaxi.com/v1/voice_clone",
}
_MINIMAX_VOICE_CLONE_DEFAULT_ENDPOINT = _MINIMAX_VOICE_CLONE_ENDPOINTS["global_en"]
_MINIMAX_VOICE_CLONE_MODELS = frozenset(
    {
        "speech-2.8-hd",
        "speech-2.6-hd",
        "speech-02-hd",
        "speech-01-hd",
    }
)
_MINIMAX_VOICE_CLONE_DEFAULT_MODEL = "speech-2.8-hd"
_MINIMAX_VOICE_CLONE_AUDIO_FORMATS = frozenset({"mp3", "m4a", "wav"})

_EXT_MIME = {
    ".png": "image/png",
    ".jpg": "image/jpeg",
    ".jpeg": "image/jpeg",
    ".webp": "image/webp",
    ".gif": "image/gif",
    ".bmp": "image/bmp",
}


class _OpenRouterMediaTool(Tool):
    """Shared base: config/env resolution, chat-completions call, file output."""

    default_model = ""

    def __init__(
        self,
        config: "MediaToolConfig | None" = None,
        *,
        workspace: Path | None = None,
        proxy: str | None = None,
        output_subdir: str = "generated",
    ):
        self._config = config
        self._workspace = Path(workspace) if workspace else Path.cwd()
        self._proxy = proxy
        self._output_subdir = output_subdir

    # ── config resolution (at call time, so env/config edits are picked up) ──

    @property
    def api_key(self) -> str:
        cfg_key = getattr(self._config, "api_key", "") if self._config else ""
        return cfg_key or os.environ.get("OPENROUTER_API_KEY", "")

    @property
    def api_base(self) -> str:
        cfg_base = getattr(self._config, "api_base", "") if self._config else ""
        return (cfg_base or _DEFAULT_BASE).rstrip("/")

    def _model(self, override: str | None) -> str:
        cfg_model = getattr(self._config, "model", "") if self._config else ""
        return override or cfg_model or self.default_model

    def _output_path(self, ext: str) -> Path:
        out_dir = self._workspace / self._output_subdir
        out_dir.mkdir(parents=True, exist_ok=True)
        return out_dir / f"{self.name}-{uuid.uuid4().hex[:12]}.{ext}"

    def _no_key_error(self) -> str:
        return json.dumps(
            {
                "error": (
                    f"{self.name}: no API key configured. Set it in "
                    f"~/.raven/config.json under tools.media.*.apiKey, "
                    f"providers.openrouter.apiKey, or export OPENROUTER_API_KEY, "
                    f"then restart the gateway."
                )
            },
            ensure_ascii=False,
        )

    async def _chat(self, payload: dict[str, Any]) -> dict[str, Any]:
        """POST to chat/completions and return the assistant message dict.

        Raises ``httpx.HTTPStatusError`` on non-2xx so callers can format it.
        """
        async with httpx.AsyncClient(proxy=self._proxy, timeout=180.0) as client:
            r = await client.post(
                f"{self.api_base}/chat/completions",
                headers={"Authorization": f"Bearer {self.api_key}", "Content-Type": "application/json"},
                json=payload,
            )
            r.raise_for_status()
            data = r.json()
        return (data.get("choices") or [{}])[0].get("message") or {}

    def _format_http_error(self, e: httpx.HTTPStatusError) -> str:
        body = e.response.text[:400]
        hint = ""
        if e.response.status_code == 403:
            hint = (
                " | Request denied (HTTP 403). You can route media calls through a "
                "proxy via tools.media.proxy (or HTTPS_PROXY) and retry."
            )
        logger.error("{} HTTP {}: {}", self.name, e.response.status_code, body)
        return json.dumps({"error": f"HTTP {e.response.status_code}: {body}{hint}"}, ensure_ascii=False)


class ImageGenerateTool(_OpenRouterMediaTool):
    """Generate (or edit) an image from a text prompt via Nano Banana on OpenRouter."""

    name = "image_generate"
    default_model = "google/gemini-2.5-flash-image"  # Nano Banana
    description = (
        "Generate an image from a text prompt (optionally editing/varying input "
        "images). Saves the image under the workspace and returns its file path; "
        "forward it to the user with the `message` tool's `media` field."
    )
    parameters = {
        "type": "object",
        "properties": {
            "prompt": {"type": "string", "description": "Text description of the image to create"},
            "model": {
                "type": "string",
                "description": (
                    "Optional OpenRouter image model override, e.g. "
                    "'google/gemini-2.5-flash-image' (Nano Banana) or "
                    "'google/gemini-3.1-flash-image-preview' (Nano Banana 2)"
                ),
            },
            "images": {
                "type": "array",
                "items": {"type": "string"},
                "description": (
                    "Optional input images to edit/vary: local file paths, http(s) URLs, or data: URIs (max 6)"
                ),
            },
        },
        "required": ["prompt"],
    }

    def _image_part(self, ref: str) -> dict[str, Any]:
        """Build an OpenAI-style image_url content part from a path/URL/data URI."""
        if ref.startswith(("http://", "https://", "data:")):
            return image_block(ref)
        path = Path(ref).expanduser()
        data = path.read_bytes()
        mime = _EXT_MIME.get(path.suffix.lower(), "image/png")
        b64 = base64.b64encode(data).decode("ascii")
        return image_block(f"data:{mime};base64,{b64}")

    async def execute(
        self,
        prompt: str,
        model: str | None = None,
        images: list[str] | None = None,
        **kwargs: Any,
    ) -> str:
        if not self.api_key:
            return self._no_key_error()

        model_id = self._model(model)
        if images:
            content: Any = [{"type": "text", "text": prompt}]
            try:
                for ref in images[:6]:
                    content.append(self._image_part(ref))
            except OSError as e:
                return json.dumps({"error": f"could not read input image: {e}"}, ensure_ascii=False)
        else:
            content = prompt

        payload = {
            "model": model_id,
            "messages": [{"role": "user", "content": content}],
            "modalities": ["image", "text"],
        }

        try:
            msg = await self._chat(payload)
        except httpx.HTTPStatusError as e:
            return self._format_http_error(e)
        except Exception as e:
            logger.error("image_generate error: {}", e)
            return json.dumps({"error": str(e)}, ensure_ascii=False)

        out_images = msg.get("images") or []
        if not out_images:
            note = msg.get("content") or msg.get("refusal") or ""
            return json.dumps(
                {"error": "no image returned", "model": model_id, "note": note[:300]},
                ensure_ascii=False,
            )

        paths: list[str] = []
        for item in out_images:
            url = (item.get("image_url") or {}).get("url", "")
            if not url.startswith("data:"):
                continue
            b64 = url.split(",", 1)[1]
            path = self._output_path("png")
            path.write_bytes(base64.b64decode(b64))
            paths.append(str(path))

        if not paths:
            return json.dumps({"error": "image payload was not a data URI", "model": model_id}, ensure_ascii=False)

        logger.info("image_generate: {} image(s) via {} -> {}", len(paths), model_id, paths)
        return json.dumps({"success": True, "model": model_id, "paths": paths}, ensure_ascii=False)


class SpeechGenerateTool(_OpenRouterMediaTool):
    """Synthesize speech from text via an OpenRouter audio model (gpt-audio)."""

    name = "text_to_speech"
    default_model = "openai/gpt-audio-mini"
    description = (
        "Synthesize speech audio from text. Saves an audio file under the "
        "workspace and returns its path; forward it with the `message` tool's "
        "`media` field."
    )
    parameters = {
        "type": "object",
        "properties": {
            "text": {"type": "string", "description": "Text to speak"},
            "voice": {
                "type": "string",
                "description": "Voice name (e.g. alloy, echo, fable, onyx, nova, shimmer)",
                "default": "alloy",
            },
            "format": {
                "type": "string",
                "enum": ["wav", "mp3", "opus", "flac"],
                "default": "wav",
                "description": (
                    "Output container. 'wav' is always available (zero deps); "
                    "mp3/opus/flac require ffmpeg on PATH and fall back to wav if absent."
                ),
            },
            "model": {
                "type": "string",
                "description": "Optional OpenRouter audio model override (e.g. openai/gpt-audio)",
            },
        },
        "required": ["text"],
    }

    # OpenRouter streams audio as raw pcm16; OpenAI's gpt-audio emits it at
    # 24 kHz, mono, 16-bit — the params needed to wrap it into a valid WAV.
    _PCM_RATE = 24_000
    _PCM_CHANNELS = 1
    _PCM_SAMPWIDTH = 2

    async def execute(
        self,
        text: str,
        voice: str = "alloy",
        format: str = "wav",
        model: str | None = None,
        **kwargs: Any,
    ) -> str:
        if not self.api_key:
            return self._no_key_error()

        model_id = self._model(model)
        payload = {
            "model": model_id,
            # Instruct verbatim narration — gpt-audio is conversational, so an
            # explicit directive keeps it from ad-libbing a reply.
            "messages": [
                {
                    "role": "user",
                    "content": f"Read the following text aloud verbatim, adding nothing:\n\n{text}",
                }
            ],
            "modalities": ["audio", "text"],
            # OpenRouter rejects audio output unless stream=true, and in stream
            # mode only the raw pcm16 format is accepted — we wrap/transcode after.
            "stream": True,
            "audio": {"voice": voice, "format": "pcm16"},
        }

        try:
            pcm, transcript = await self._stream_audio_pcm(payload)
        except httpx.HTTPStatusError as e:
            return self._format_http_error(e)
        except Exception as e:
            logger.error("text_to_speech error: {}", e)
            return json.dumps({"error": str(e)}, ensure_ascii=False)

        if not pcm:
            return json.dumps(
                {"error": "no audio returned", "model": model_id, "note": transcript[:300]},
                ensure_ascii=False,
            )

        wav_path = self._output_path("wav")
        self._write_wav(wav_path, pcm)
        out_path, out_fmt, note = await self._maybe_transcode(wav_path, format)

        logger.info("text_to_speech: via {} -> {}", model_id, out_path)
        result: dict[str, Any] = {
            "success": True,
            "model": model_id,
            "path": str(out_path),
            "format": out_fmt,
        }
        if transcript:
            result["transcript"] = transcript
        if note:
            result["note"] = note
        return json.dumps(result, ensure_ascii=False)

    async def _stream_audio_pcm(self, payload: dict[str, Any]) -> tuple[bytes, str]:
        """Stream a chat-completions audio response → (pcm16 bytes, transcript).

        Concatenates the base64 ``delta.audio.data`` chunks (and any transcript
        text) from the SSE stream. Raises ``httpx.HTTPStatusError`` on non-2xx so
        ``execute`` can format it the same way as the image path.
        """
        pcm = bytearray()
        transcript_parts: list[str] = []
        headers = {
            "Authorization": f"Bearer {self.api_key}",
            "Content-Type": "application/json",
        }
        async with httpx.AsyncClient(proxy=self._proxy, timeout=180.0) as client:
            async with client.stream("POST", f"{self.api_base}/chat/completions", headers=headers, json=payload) as r:
                if r.status_code >= 400:
                    await r.aread()  # load body so .text/raise_for_status carry the error
                    r.raise_for_status()
                async for line in r.aiter_lines():
                    if not line.startswith("data:"):
                        continue
                    data = line[len("data:") :].strip()
                    if data == "[DONE]":
                        break
                    try:
                        obj = json.loads(data)
                    except json.JSONDecodeError:
                        continue
                    delta = (obj.get("choices") or [{}])[0].get("delta") or {}
                    audio = delta.get("audio") or {}
                    if chunk := audio.get("data"):
                        pcm += base64.b64decode(chunk)
                    if t := audio.get("transcript"):
                        transcript_parts.append(t)
        return bytes(pcm), "".join(transcript_parts)

    def _write_wav(self, path: Path, pcm: bytes) -> None:
        """Wrap raw pcm16 bytes into a WAV container (stdlib, no deps)."""
        with wave.open(str(path), "wb") as w:
            w.setnchannels(self._PCM_CHANNELS)
            w.setsampwidth(self._PCM_SAMPWIDTH)
            w.setframerate(self._PCM_RATE)
            w.writeframes(pcm)

    async def _maybe_transcode(self, wav_path: Path, fmt: str) -> tuple[Path, str, str]:
        """Transcode the WAV to ``fmt`` via ffmpeg. Returns (path, format, note).

        wav needs nothing; other formats need ffmpeg and fall back to wav with a
        note when it is missing or the conversion fails.
        """
        if fmt == "wav":
            return wav_path, "wav", ""
        ffmpeg = shutil.which("ffmpeg")
        if not ffmpeg:
            return wav_path, "wav", f"ffmpeg not on PATH; saved as wav instead of {fmt}"
        out = wav_path.with_suffix(f".{fmt}")
        proc = await asyncio.create_subprocess_exec(
            ffmpeg,
            "-y",
            "-i",
            str(wav_path),
            str(out),
            stdout=asyncio.subprocess.DEVNULL,
            stderr=asyncio.subprocess.PIPE,
        )
        _, err = await proc.communicate()
        if proc.returncode != 0 or not out.exists():
            logger.warning("ffmpeg transcode to {} failed: {}", fmt, err.decode("utf-8", "replace")[:200])
            return wav_path, "wav", f"ffmpeg transcode to {fmt} failed; saved as wav"
        wav_path.unlink(missing_ok=True)
        return out, fmt, ""


class VoiceCloneTool(_OpenRouterMediaTool):
    """Create a reusable MiniMax voice from a local audio sample."""

    name = "voice_clone"
    default_model = _MINIMAX_VOICE_CLONE_DEFAULT_MODEL
    description = (
        "Clone a voice from a local MP3, M4A, or WAV sample. Optionally upload a "
        "second short prompt sample to improve similarity."
    )
    parameters = {
        "type": "object",
        "properties": {
            "audio_path": {"type": "string", "description": "Local path to the voice sample"},
            "voice_id": {"type": "string", "description": "Unique identifier to assign to the cloned voice"},
            "model": {
                "type": "string",
                "enum": sorted(_MINIMAX_VOICE_CLONE_MODELS),
                "default": _MINIMAX_VOICE_CLONE_DEFAULT_MODEL,
                "description": "Speech model used to validate the cloned voice",
            },
            "prompt_audio_path": {
                "type": "string",
                "description": "Optional local path to a prompt sample shorter than eight seconds",
            },
            "prompt_text": {
                "type": "string",
                "description": "Transcript of prompt_audio_path, including ending punctuation",
            },
            "text": {"type": "string", "description": "Optional text for a preview audio sample"},
            "text_validation": {
                "type": "string",
                "description": "Optional expected transcript for validating the source audio",
            },
            "accuracy": {
                "type": "number",
                "minimum": 0,
                "maximum": 1,
                "default": 0.7,
                "description": "Minimum transcript similarity when text_validation is provided",
            },
            "need_noise_reduction": {"type": "boolean", "default": False},
            "need_volume_normalization": {"type": "boolean", "default": False},
            "aigc_watermark": {"type": "boolean", "default": False},
        },
        "required": ["audio_path", "voice_id"],
    }

    @property
    def _minimax_api_key(self) -> str:
        cfg_key = getattr(self._config, "api_key", "") if self._config else ""
        return cfg_key or os.environ.get("MINIMAX_API_KEY", "")

    @property
    def _clone_endpoint(self) -> str:
        cfg_base = getattr(self._config, "api_base", "") if self._config else ""
        if not cfg_base:
            return _MINIMAX_VOICE_CLONE_DEFAULT_ENDPOINT
        base = cfg_base.rstrip("/")
        return base if base.endswith("/voice_clone") else f"{base}/voice_clone"

    @property
    def _upload_endpoint(self) -> str:
        return f"{self._clone_endpoint.rsplit('/voice_clone', 1)[0]}/files/upload"

    def _no_minimax_key_error(self) -> str:
        return json.dumps(
            {
                "error": (
                    "voice_clone: no API key configured. Set it under "
                    "tools.media.voiceClone.apiKey or providers.minimax.apiKey, "
                    "or export MINIMAX_API_KEY, then restart the gateway."
                )
            },
            ensure_ascii=False,
        )

    @staticmethod
    def _response_error(response: dict[str, Any]) -> str:
        base_resp = response.get("base_resp") or {}
        status_code = base_resp.get("status_code")
        if status_code in (None, 0):
            return ""
        return str(base_resp.get("status_msg") or f"status_code={status_code}")

    async def _upload_audio(
        self,
        client: httpx.AsyncClient,
        path: Path,
        purpose: str,
        headers: dict[str, str],
    ) -> int | str:
        suffix = path.suffix.lower().lstrip(".")
        if suffix not in _MINIMAX_VOICE_CLONE_AUDIO_FORMATS:
            supported = ", ".join(sorted(_MINIMAX_VOICE_CLONE_AUDIO_FORMATS))
            raise ValueError(f"unsupported audio format: {suffix or 'unknown'}; expected one of {supported}")
        response = await client.post(
            self._upload_endpoint,
            headers=headers,
            data={"purpose": purpose},
            files={"file": (path.name, path.read_bytes(), "application/octet-stream")},
        )
        response.raise_for_status()
        payload = response.json()
        if error := self._response_error(payload):
            raise ValueError(error)
        file_id = (payload.get("file") or {}).get("file_id")
        if file_id in (None, ""):
            raise ValueError("file upload did not return file.file_id")
        return file_id

    async def execute(
        self,
        audio_path: str,
        voice_id: str,
        model: str | None = None,
        prompt_audio_path: str | None = None,
        prompt_text: str | None = None,
        text: str | None = None,
        text_validation: str | None = None,
        accuracy: float = 0.7,
        need_noise_reduction: bool = False,
        need_volume_normalization: bool = False,
        aigc_watermark: bool = False,
        **kwargs: Any,
    ) -> str:
        if not self._minimax_api_key:
            return self._no_minimax_key_error()
        if bool(prompt_audio_path) != bool(prompt_text):
            return json.dumps(
                {"error": "prompt_audio_path and prompt_text must be provided together"},
                ensure_ascii=False,
            )

        model_id = self._model(model)
        if model_id not in _MINIMAX_VOICE_CLONE_MODELS:
            return json.dumps({"error": f"unsupported voice cloning model: {model_id}"}, ensure_ascii=False)

        source = Path(audio_path).expanduser()
        prompt_source = Path(prompt_audio_path).expanduser() if prompt_audio_path else None
        for path in (source, prompt_source):
            if path is not None and not path.is_file():
                return json.dumps({"error": f"audio file not found: {path}"}, ensure_ascii=False)

        headers = {"Authorization": f"Bearer {self._minimax_api_key}"}
        try:
            async with httpx.AsyncClient(proxy=self._proxy, timeout=180.0) as client:
                file_id = await self._upload_audio(client, source, "voice_clone", headers)
                payload: dict[str, Any] = {
                    "file_id": file_id,
                    "voice_id": voice_id,
                    "model": model_id,
                    "accuracy": accuracy,
                    "need_noise_reduction": need_noise_reduction,
                    "need_volume_normalization": need_volume_normalization,
                    "aigc_watermark": aigc_watermark,
                }
                if prompt_source is not None:
                    prompt_file_id = await self._upload_audio(client, prompt_source, "prompt_audio", headers)
                    payload["clone_prompt"] = {
                        "prompt_audio": prompt_file_id,
                        "prompt_text": prompt_text,
                    }
                if text is not None:
                    payload["text"] = text
                if text_validation is not None:
                    payload["text_validation"] = text_validation

                response = await client.post(
                    self._clone_endpoint,
                    headers={**headers, "Content-Type": "application/json"},
                    json=payload,
                )
                response.raise_for_status()
                result = response.json()
                if error := self._response_error(result):
                    return json.dumps({"error": error, "voice_id": voice_id}, ensure_ascii=False)
        except httpx.HTTPStatusError as e:
            return self._format_http_error(e)
        except Exception as e:
            logger.error("voice_clone error: {}", e)
            return json.dumps({"error": str(e)}, ensure_ascii=False)

        result_voice_id = result.get("voice_id") or voice_id
        logger.info("voice_clone: created {} via {}", result_voice_id, model_id)
        return json.dumps(
            {"success": True, "voice_id": result_voice_id, "model": model_id},
            ensure_ascii=False,
        )


def _find_video_url(obj: Any) -> str | None:
    """Recursively find the first downloadable video URL / data URI in a response.

    The exact completed-response shape for OpenRouter's /videos endpoint is not
    publicly pinned down, so we search defensively rather than hard-code a path.
    """
    if isinstance(obj, str):
        s = obj
        if s.startswith("data:video") or (
            s.startswith(("http://", "https://"))
            and any(ext in s.lower() for ext in (".mp4", ".webm", ".mov", "video"))
        ):
            return s
        return None
    if isinstance(obj, dict):
        # Prefer obvious keys first.
        for key in ("url", "video_url", "download_url", "video", "output", "result"):
            if key in obj and (found := _find_video_url(obj[key])):
                return found
        for v in obj.values():
            if found := _find_video_url(v):
                return found
        return None
    if isinstance(obj, list):
        for item in obj:
            if found := _find_video_url(item):
                return found
        return None
    return None


def _pick_video_url(status: dict[str, Any]) -> str | None:
    """Choose the downloadable content URL from a completed /videos response.

    OpenRouter's completed shape exposes the rendered video under
    ``signed_urls`` / ``unsigned_urls`` (lists). We prefer those explicitly:
    the job's own ``polling_url`` also lives under ``/videos/`` and would
    otherwise be matched by ``_find_video_url``'s "video" substring heuristic,
    yielding the status JSON instead of the clip. For any other (undocumented)
    provider shape we fall back to a defensive scan that excludes the
    polling/status URL.
    """
    for key in ("signed_urls", "unsigned_urls"):
        urls = status.get(key)
        if isinstance(urls, list) and urls and isinstance(urls[0], str):
            return urls[0]
    scannable = {k: v for k, v in status.items() if k != "polling_url"}
    return _find_video_url(scannable)


class VideoGenerateTool(_OpenRouterMediaTool):
    """Generate a video from a text prompt via Kling on OpenRouter (async)."""

    name = "video_generate"
    default_model = "kwaivgi/kling-v3.0-std"  # Kling v3 Standard
    description = (
        "Generate a short video from a text prompt (async; takes a while). Saves "
        "the video under the workspace and returns its path; forward it with the "
        "`message` tool's `media` field."
    )
    parameters = {
        "type": "object",
        "properties": {
            "prompt": {"type": "string", "description": "Text description of the video"},
            "model": {
                "type": "string",
                "description": "Optional OpenRouter video model override (default kwaivgi/kling-v3.0-std)",
            },
            "params": {
                "type": "object",
                "description": (
                    "Optional extra provider params merged into the request, e.g. "
                    '{"duration": 5, "aspect_ratio": "16:9"} (3-15s; 16:9/9:16/1:1)'
                ),
            },
        },
        "required": ["prompt"],
    }

    _POLL_INTERVAL_S = 6.0
    _POLL_TIMEOUT_S = 600.0
    # Backstop above the 600s polling cap; the poll loop gives up first.
    timeout_seconds = 660.0

    async def execute(
        self,
        prompt: str,
        model: str | None = None,
        params: dict[str, Any] | None = None,
        **kwargs: Any,
    ) -> str:
        if not self.api_key:
            return self._no_key_error()

        model_id = self._model(model)
        body: dict[str, Any] = {"model": model_id, "prompt": prompt}
        if params:
            body.update(params)

        headers = {"Authorization": f"Bearer {self.api_key}", "Content-Type": "application/json"}
        try:
            async with httpx.AsyncClient(proxy=self._proxy, timeout=120.0) as client:
                # 1) submit job
                r = await client.post(f"{self.api_base}/videos", headers=headers, json=body)
                r.raise_for_status()
                job = r.json()
                poll_url = job.get("polling_url") or f"{self.api_base}/videos/{job.get('id')}"

                # 2) poll
                status = await self._poll(client, poll_url, headers)
                state = status.get("status")
                if state != "completed":
                    return json.dumps(
                        {
                            "error": f"video job status={state}",
                            "detail": status.get("error") or status,
                            "model": model_id,
                        },
                        ensure_ascii=False,
                    )

                # 3) locate + download the video
                video_url = _pick_video_url(status)
                if not video_url:
                    return json.dumps(
                        {"error": "completed but no video URL found", "raw": status},
                        ensure_ascii=False,
                    )
                if video_url.startswith("data:"):
                    data = base64.b64decode(video_url.split(",", 1)[1])
                else:
                    # OpenRouter returns "unsigned" content URLs on its own host
                    # that need the same Authorization header as the API. Only
                    # send it to OpenRouter — never leak the key to a third-party
                    # (pre-signed CDN/S3) host.
                    dl_headers = headers if video_url.startswith(self.api_base) else None
                    dl = await client.get(video_url, headers=dl_headers, timeout=180.0)
                    dl.raise_for_status()
                    data = dl.content
        except httpx.HTTPStatusError as e:
            return self._format_http_error(e)
        except Exception as e:
            logger.error("video_generate error: {}", e)
            return json.dumps({"error": str(e)}, ensure_ascii=False)

        path = self._output_path("mp4")
        path.write_bytes(data)
        logger.info("video_generate: {} bytes via {} -> {}", len(data), model_id, path)
        return json.dumps({"success": True, "model": model_id, "path": str(path)}, ensure_ascii=False)

    async def _poll(self, client: httpx.AsyncClient, poll_url: str, headers: dict[str, str]) -> dict[str, Any]:
        """Poll until the job leaves the pending/processing state or times out."""
        waited = 0.0
        while waited < self._POLL_TIMEOUT_S:
            r = await client.get(poll_url, headers=headers)
            r.raise_for_status()
            job = r.json()
            if job.get("status") not in ("pending", "processing", "queued", "in_progress"):
                return job
            await asyncio.sleep(self._POLL_INTERVAL_S)
            waited += self._POLL_INTERVAL_S
        return {"status": "timeout"}
