"""Multimodal generation tools.

OpenRouter exposes generation through the OpenAI-compatible chat-completions
API with extra *output modalities* — there are no standalone
``/images/generations`` or ``/audio/speech`` endpoints. Both tools here POST
to ``{base}/chat/completions`` with a ``modalities`` array and read the
generated bytes back from the assistant message:

- ``image_generate``  → ``modalities:["image","text"]`` → ``message.images[].image_url.url``
  (a ``data:image/...;base64,...`` URI). Default model **Nano Banana**
  (``google/gemini-2.5-flash-image``).
- ``text_to_speech``  → ``modalities:["audio","text"]`` + ``audio:{voice,format}``.
  OpenRouter only returns audio when ``stream:true`` AND only as raw ``pcm16``
  in that mode, so we stream, concatenate the base64 ``delta.audio.data`` chunks,
  and wrap the PCM (24 kHz / mono / 16-bit) into a WAV with the stdlib ``wave``
  module — zero binary dependency. mp3/opus/flac are transcoded from that WAV
  only when ``ffmpeg`` is on PATH; otherwise we keep the WAV and say so.
  Default model ``openai/gpt-audio-mini``.

MiniMax speech uses its dedicated HTTP API:

- ``text_to_speech`` → ``POST {base}/t2a_v2`` with ``{model, text, ...}``.
  The global endpoint is used by default; setting ``tools.media.speech.apiBase``
  selects the China endpoint. Audio is returned through ``data.audio`` as
  hex bytes or a short-lived URL, ``data.status`` reports generation state,
  and success is reported by ``base_resp.status_code``.

Video uses a separate async endpoint (NOT chat-completions):

- ``video_generate``  → ``POST {base}/videos`` with ``{model, prompt}`` → ``202``
  ``{id, polling_url, status}`` → poll ``polling_url`` until ``completed`` (URLs
  to download) or ``failed`` (with ``error``). Default model
  ``kwaivgi/kling-v3.0-std`` (Kling v3 Standard). Requires postpaid billing /
  credits enabled on the OpenRouter account.

Generated files are written under ``<workspace>/<output_subdir>`` and the path
is returned so the agent can forward it with the ``message`` tool's ``media``
field. A denied request (HTTP 403) hints at setting ``tools.media.proxy``.

See demos/skill_retrieval/skills/image-gen/SKILL.md for the image recipe.
"""

from __future__ import annotations

import asyncio
import base64
import json
import os
import shutil
import uuid
import wave
from pathlib import Path
from typing import TYPE_CHECKING, Any

import httpx
from loguru import logger

from raven.agent.tools.base import Tool
from raven.utils.helpers import image_block

if TYPE_CHECKING:
    from raven.config.schema import MediaToolConfig

_DEFAULT_BASE = "https://openrouter.ai/api/v1"
_MINIMAX_SPEECH_ENDPOINTS = {
    "global_en": "https://api.minimax.io/v1/t2a_v2",
    "cn_zh": "https://api.minimaxi.com/v1/t2a_v2",
}
_MINIMAX_SPEECH_DEFAULT_ENDPOINT = _MINIMAX_SPEECH_ENDPOINTS["global_en"]
_MINIMAX_SPEECH_MODELS = frozenset(
    {
        "speech-2.8-hd",
        "speech-2.8-turbo",
        "speech-2.6-hd",
        "speech-2.6-turbo",
        "speech-02-hd",
        "speech-02-turbo",
        "speech-01-hd",
        "speech-01-turbo",
    }
)
_MINIMAX_SPEECH_DEFAULT_MODEL = "speech-2.8-hd"
_MINIMAX_SPEECH_AUDIO_FORMATS = frozenset({"mp3", "wav", "flac", "pcm"})
_MINIMAX_SPEECH_HOSTS = tuple(endpoint.split("/")[2] for endpoint in _MINIMAX_SPEECH_ENDPOINTS.values())

_EXT_MIME = {
    ".png": "image/png",
    ".jpg": "image/jpeg",
    ".jpeg": "image/jpeg",
    ".webp": "image/webp",
    ".gif": "image/gif",
    ".bmp": "image/bmp",
}


class _OpenRouterMediaTool(Tool):
    """Shared base: config/env resolution, chat-completions call, file output."""

    default_model = ""

    def __init__(
        self,
        config: "MediaToolConfig | None" = None,
        *,
        workspace: Path | None = None,
        proxy: str | None = None,
        output_subdir: str = "generated",
    ):
        self._config = config
        self._workspace = Path(workspace) if workspace else Path.cwd()
        self._proxy = proxy
        self._output_subdir = output_subdir

    # ── config resolution (at call time, so env/config edits are picked up) ──

    @staticmethod
    def _resolve_key(config: "MediaToolConfig | None") -> str:
        """The credential chain in one place: this tool's section, then the
        shared environment variable.

        A static method so :meth:`has_key` can ask it without an instance --
        this base is abstract, and the callers deciding whether a capability
        works hold a config and no tool.
        """
        cfg_key = getattr(config, "api_key", "") if config else ""
        return cfg_key or os.environ.get("OPENROUTER_API_KEY", "")

    @property
    def api_key(self) -> str:
        return self._resolve_key(self._config)

    @classmethod
    def is_configured(cls, config: "MediaToolConfig | None") -> bool:
        """Whether this deployment asked for the tool at all.

        A model *or* a key, matching what ``AgentLoop`` registers on: the key
        alone would let an OpenRouter credential set for chat quietly switch on
        three tools that bill per call, and the model alone would miss the
        deployment that names no model and relies on ``default_model``.

        A classmethod because the caller deciding whether to offer the tool has
        a config and no instance, and because the answer has to be askable
        without building one.
        """
        if config is None:
            return False
        return bool(config.api_key or config.model)

    @classmethod
    def has_key(cls, config: "MediaToolConfig | None") -> bool:
        """Whether a credential resolves for this tool.

        A different question from :meth:`is_configured`, which answers whether
        the deployment asked for the tool at all: a section naming only a model
        is registered and offered to the model, and then every call returns
        :meth:`_no_key_error`. Asked of the tool because only the tool consults
        both the section and ``OPENROUTER_API_KEY``, so a caller reading the
        config alone answers wrong for every deployment that exports it.
        """
        return bool(cls._resolve_key(config))

    @property
    def api_base(self) -> str:
        cfg_base = getattr(self._config, "api_base", "") if self._config else ""
        return (cfg_base or _DEFAULT_BASE).rstrip("/")

    def _model(self, override: str | None) -> str:
        cfg_model = getattr(self._config, "model", "") if self._config else ""
        return override or cfg_model or self.default_model

    def _output_path(self, ext: str) -> Path:
        out_dir = self._workspace / self._output_subdir
        out_dir.mkdir(parents=True, exist_ok=True)
        return out_dir / f"{self.name}-{uuid.uuid4().hex[:12]}.{ext}"

    def _no_key_error(self) -> str:
        return json.dumps(
            {
                "error": (
                    f"{self.name}: no API key configured. Set it in "
                    f"~/.raven/config.json under tools.media.*.apiKey, "
                    f"providers.openrouter.apiKey, or export OPENROUTER_API_KEY, "
                    f"then restart the gateway."
                )
            },
            ensure_ascii=False,
        )

    async def _chat(self, payload: dict[str, Any]) -> dict[str, Any]:
        """POST to chat/completions and return the assistant message dict.

        Raises ``httpx.HTTPStatusError`` on non-2xx so callers can format it.
        """
        async with httpx.AsyncClient(proxy=self._proxy, timeout=180.0) as client:
            r = await client.post(
                f"{self.api_base}/chat/completions",
                headers={"Authorization": f"Bearer {self.api_key}", "Content-Type": "application/json"},
                json=payload,
            )
            r.raise_for_status()
            data = r.json()
        return (data.get("choices") or [{}])[0].get("message") or {}

    def _format_http_error(self, e: httpx.HTTPStatusError) -> str:
        body = e.response.text[:400]
        hint = ""
        if e.response.status_code == 403:
            hint = (
                " | Request denied (HTTP 403). You can route media calls through a "
                "proxy via tools.media.proxy (or HTTPS_PROXY) and retry."
            )
        logger.error("{} HTTP {}: {}", self.name, e.response.status_code, body)
        return json.dumps({"error": f"HTTP {e.response.status_code}: {body}{hint}"}, ensure_ascii=False)


class ImageGenerateTool(_OpenRouterMediaTool):
    """Generate (or edit) an image from a text prompt via Nano Banana on OpenRouter."""

    name = "image_generate"
    default_model = "google/gemini-2.5-flash-image"  # Nano Banana
    description = (
        "Generate an image from a text prompt (optionally editing/varying input "
        "images). Saves the image under the workspace and returns its file path; "
        "forward it to the user with the `message` tool's `media` field."
    )
    parameters = {
        "type": "object",
        "properties": {
            "prompt": {"type": "string", "description": "Text description of the image to create"},
            "model": {
                "type": "string",
                "description": (
                    "Optional OpenRouter image model override, e.g. "
                    "'google/gemini-2.5-flash-image' (Nano Banana) or "
                    "'google/gemini-3.1-flash-image-preview' (Nano Banana 2)"
                ),
            },
            "images": {
                "type": "array",
                "items": {"type": "string"},
                "description": (
                    "Optional input images to edit/vary: local file paths, http(s) URLs, or data: URIs (max 6)"
                ),
            },
        },
        "required": ["prompt"],
    }

    def _image_part(self, ref: str) -> dict[str, Any]:
        """Build an OpenAI-style image_url content part from a path/URL/data URI."""
        if ref.startswith(("http://", "https://", "data:")):
            return image_block(ref)
        path = Path(ref).expanduser()
        data = path.read_bytes()
        mime = _EXT_MIME.get(path.suffix.lower(), "image/png")
        b64 = base64.b64encode(data).decode("ascii")
        return image_block(f"data:{mime};base64,{b64}")

    async def execute(
        self,
        prompt: str,
        model: str | None = None,
        images: list[str] | None = None,
        **kwargs: Any,
    ) -> str:
        if not self.api_key:
            return self._no_key_error()

        model_id = self._model(model)
        if images:
            content: Any = [{"type": "text", "text": prompt}]
            try:
                for ref in images[:6]:
                    content.append(self._image_part(ref))
            except OSError as e:
                return json.dumps({"error": f"could not read input image: {e}"}, ensure_ascii=False)
        else:
            content = prompt

        payload = {
            "model": model_id,
            "messages": [{"role": "user", "content": content}],
            "modalities": ["image", "text"],
        }

        try:
            msg = await self._chat(payload)
        except httpx.HTTPStatusError as e:
            return self._format_http_error(e)
        except Exception as e:
            logger.error("image_generate error: {}", e)
            return json.dumps({"error": str(e)}, ensure_ascii=False)

        out_images = msg.get("images") or []
        if not out_images:
            note = msg.get("content") or msg.get("refusal") or ""
            return json.dumps(
                {"error": "no image returned", "model": model_id, "note": note[:300]},
                ensure_ascii=False,
            )

        paths: list[str] = []
        for item in out_images:
            url = (item.get("image_url") or {}).get("url", "")
            if not url.startswith("data:"):
                continue
            b64 = url.split(",", 1)[1]
            path = self._output_path("png")
            path.write_bytes(base64.b64decode(b64))
            paths.append(str(path))

        if not paths:
            return json.dumps({"error": "image payload was not a data URI", "model": model_id}, ensure_ascii=False)

        logger.info("image_generate: {} image(s) via {} -> {}", len(paths), model_id, paths)
        return json.dumps({"success": True, "model": model_id, "paths": paths}, ensure_ascii=False)


class SpeechGenerateTool(_OpenRouterMediaTool):
    """Synthesize speech from text through a configured speech backend."""

    name = "text_to_speech"
    default_model = "openai/gpt-audio-mini"
    description = (
        "Synthesize speech audio from text. Saves an audio file under the "
        "workspace and returns its path; forward it with the `message` tool's "
        "`media` field."
    )
    parameters = {
        "type": "object",
        "properties": {
            "text": {"type": "string", "description": "Text to speak"},
            "voice": {
                "type": "string",
                "description": "Voice name (e.g. alloy, echo, fable, onyx, nova, shimmer)",
                "default": "alloy",
            },
            "format": {
                "type": "string",
                "enum": ["wav", "mp3", "opus", "flac"],
                "default": "wav",
                "description": (
                    "Output container. 'wav' is always available (zero deps); "
                    "mp3/opus/flac require ffmpeg on PATH and fall back to wav if absent."
                ),
            },
            "model": {
                "type": "string",
                "description": "Optional OpenRouter audio model override (e.g. openai/gpt-audio)",
            },
            "stream": {"type": "boolean", "default": False, "description": "Stream generated audio"},
            "language_boost": {"type": "string", "description": "Optional language recognition hint"},
            "output_format": {
                "type": "string",
                "enum": ["hex", "url"],
                "default": "hex",
                "description": "MiniMax response encoding; streaming requires hex",
            },
            "voice_setting": {"type": "object", "description": "MiniMax voice settings"},
            "pronunciation_dict": {"type": "object", "description": "MiniMax pronunciation replacements"},
            "audio_setting": {"type": "object", "description": "MiniMax audio encoding settings"},
            "voice_modify": {"type": "object", "description": "MiniMax voice effect settings"},
            "subtitle_enable": {"type": "boolean", "description": "Include subtitle metadata"},
        },
        "required": ["text"],
    }

    # OpenRouter streams audio as raw pcm16; OpenAI's gpt-audio emits it at
    # 24 kHz, mono, 16-bit — the params needed to wrap it into a valid WAV.
    _PCM_RATE = 24_000
    _PCM_CHANNELS = 1
    _PCM_SAMPWIDTH = 2

    async def execute(
        self,
        text: str,
        voice: str = "alloy",
        format: str = "wav",
        model: str | None = None,
        stream: bool = False,
        language_boost: str | None = None,
        output_format: str = "hex",
        voice_setting: dict[str, Any] | None = None,
        pronunciation_dict: dict[str, Any] | None = None,
        audio_setting: dict[str, Any] | None = None,
        voice_modify: dict[str, Any] | None = None,
        subtitle_enable: bool | None = None,
        **kwargs: Any,
    ) -> str:
        minimax_model = self._minimax_model(model)
        if minimax_model:
            return await self._execute_minimax(
                text=text,
                model_id=minimax_model,
                stream=stream,
                language_boost=language_boost,
                output_format=output_format,
                voice_setting=voice_setting,
                pronunciation_dict=pronunciation_dict,
                audio_setting=audio_setting,
                voice_modify=voice_modify,
                subtitle_enable=subtitle_enable,
            )

        if not self.api_key:
            return self._no_key_error()

        model_id = self._model(model)
        payload = {
            "model": model_id,
            # Instruct verbatim narration — gpt-audio is conversational, so an
            # explicit directive keeps it from ad-libbing a reply.
            "messages": [
                {
                    "role": "user",
                    "content": f"Read the following text aloud verbatim, adding nothing:\n\n{text}",
                }
            ],
            "modalities": ["audio", "text"],
            # OpenRouter rejects audio output unless stream=true, and in stream
            # mode only the raw pcm16 format is accepted — we wrap/transcode after.
            "stream": True,
            "audio": {"voice": voice, "format": "pcm16"},
        }

        try:
            pcm, transcript = await self._stream_audio_pcm(payload)
        except httpx.HTTPStatusError as e:
            return self._format_http_error(e)
        except Exception as e:
            logger.error("text_to_speech error: {}", e)
            return json.dumps({"error": str(e)}, ensure_ascii=False)

        if not pcm:
            return json.dumps(
                {"error": "no audio returned", "model": model_id, "note": transcript[:300]},
                ensure_ascii=False,
            )

        wav_path = self._output_path("wav")
        self._write_wav(wav_path, pcm)
        out_path, out_fmt, note = await self._maybe_transcode(wav_path, format)

        logger.info("text_to_speech: via {} -> {}", model_id, out_path)
        result: dict[str, Any] = {
            "success": True,
            "model": model_id,
            "path": str(out_path),
            "format": out_fmt,
        }
        if transcript:
            result["transcript"] = transcript
        if note:
            result["note"] = note
        return json.dumps(result, ensure_ascii=False)

    def _minimax_model(self, override: str | None) -> str | None:
        cfg_model = getattr(self._config, "model", "") if self._config else ""
        candidate = override or cfg_model
        bare_model = candidate.rsplit("/", 1)[-1] if candidate else ""
        if bare_model in _MINIMAX_SPEECH_MODELS:
            return bare_model

        cfg_base = getattr(self._config, "api_base", "") if self._config else ""
        if any(host in cfg_base.lower() for host in _MINIMAX_SPEECH_HOSTS):
            return candidate or _MINIMAX_SPEECH_DEFAULT_MODEL
        return None

    @property
    def _minimax_api_key(self) -> str:
        cfg_key = getattr(self._config, "api_key", "") if self._config else ""
        return cfg_key or os.environ.get("MINIMAX_API_KEY", "")

    @property
    def _minimax_endpoint(self) -> str:
        cfg_base = getattr(self._config, "api_base", "") if self._config else ""
        if not cfg_base:
            return _MINIMAX_SPEECH_DEFAULT_ENDPOINT
        base = cfg_base.rstrip("/")
        return base if base.endswith("/t2a_v2") else f"{base}/t2a_v2"

    def _no_minimax_key_error(self) -> str:
        return json.dumps(
            {
                "error": (
                    "text_to_speech: no API key configured. Set it under "
                    "tools.media.speech.apiKey or providers.minimax.apiKey, "
                    "or export MINIMAX_API_KEY, then restart the gateway."
                )
            },
            ensure_ascii=False,
        )

    async def _execute_minimax(
        self,
        *,
        text: str,
        model_id: str,
        stream: bool,
        language_boost: str | None,
        output_format: str,
        voice_setting: dict[str, Any] | None,
        pronunciation_dict: dict[str, Any] | None,
        audio_setting: dict[str, Any] | None,
        voice_modify: dict[str, Any] | None,
        subtitle_enable: bool | None,
    ) -> str:
        if not self._minimax_api_key:
            return self._no_minimax_key_error()
        if output_format not in {"hex", "url"}:
            return json.dumps({"error": f"unsupported output_format: {output_format}"}, ensure_ascii=False)
        if stream and output_format != "hex":
            return json.dumps({"error": "MiniMax streaming requires output_format='hex'"}, ensure_ascii=False)

        audio = dict(audio_setting or {})
        audio_format = str(audio.get("format") or "mp3").lower()
        if audio_format not in _MINIMAX_SPEECH_AUDIO_FORMATS:
            supported = ", ".join(sorted(_MINIMAX_SPEECH_AUDIO_FORMATS))
            return json.dumps(
                {"error": f"unsupported MiniMax audio format: {audio_format}; expected one of {supported}"},
                ensure_ascii=False,
            )
        if stream and audio_format != "mp3":
            return json.dumps({"error": "MiniMax streaming supports only mp3 audio"}, ensure_ascii=False)
        audio["format"] = audio_format

        payload: dict[str, Any] = {
            "model": model_id,
            "text": text,
            "stream": stream,
            "output_format": output_format,
            "audio_setting": audio,
        }
        if voice_setting is not None:
            payload["voice_setting"] = dict(voice_setting)
        if language_boost is not None:
            payload["language_boost"] = language_boost
        if pronunciation_dict is not None:
            payload["pronunciation_dict"] = pronunciation_dict
        if voice_modify is not None:
            payload["voice_modify"] = voice_modify
        if subtitle_enable is not None:
            payload["subtitle_enable"] = subtitle_enable

        headers = {
            "Authorization": f"Bearer {self._minimax_api_key}",
            "Content-Type": "application/json",
        }
        try:
            async with httpx.AsyncClient(proxy=self._proxy, timeout=180.0) as client:
                if stream:
                    response = await self._stream_minimax_response(client, headers, payload)
                else:
                    r = await client.post(self._minimax_endpoint, headers=headers, json=payload)
                    r.raise_for_status()
                    response = r.json()

                if error := self._minimax_response_error(response):
                    return json.dumps({"error": error, "model": model_id}, ensure_ascii=False)
                data = response.get("data") or {}
                audio_value = data.get("audio")
                if not audio_value:
                    status = data.get("status")
                    message = f"speech generation status={status}" if status is not None else "no audio returned"
                    return json.dumps({"error": message, "model": model_id}, ensure_ascii=False)

                reported_format = str((response.get("extra_info") or {}).get("audio_format") or audio_format).lower()
                saved_format = reported_format if reported_format in _MINIMAX_SPEECH_AUDIO_FORMATS else audio_format
                if output_format == "url":
                    out_path = await self._download_minimax_audio(client, audio_value, saved_format)
                else:
                    if not isinstance(audio_value, str):
                        raise ValueError("MiniMax data.audio must be a hex string")
                    out_path = self._output_path(saved_format)
                    out_path.write_bytes(bytes.fromhex(audio_value))
        except httpx.HTTPStatusError as e:
            return self._format_http_error(e)
        except Exception as e:
            logger.error("text_to_speech MiniMax error: {}", e)
            return json.dumps({"error": str(e)}, ensure_ascii=False)

        logger.info("text_to_speech: via {} -> {}", model_id, out_path)
        return json.dumps(
            {"success": True, "model": model_id, "path": str(out_path), "format": saved_format},
            ensure_ascii=False,
        )

    async def _stream_minimax_response(
        self,
        client: httpx.AsyncClient,
        headers: dict[str, str],
        payload: dict[str, Any],
    ) -> dict[str, Any]:
        audio_parts: list[str] = []
        base_resp: dict[str, Any] = {}
        extra_info: dict[str, Any] = {}
        status: Any = None

        async with client.stream("POST", self._minimax_endpoint, headers=headers, json=payload) as r:
            if r.status_code >= 400:
                await r.aread()
                r.raise_for_status()
            async for line in r.aiter_lines():
                raw = line.strip()
                if raw.startswith("data:"):
                    raw = raw[len("data:") :].strip()
                if not raw or raw == "[DONE]":
                    continue
                try:
                    obj = json.loads(raw)
                except json.JSONDecodeError:
                    continue
                if not isinstance(obj, dict):
                    continue
                if isinstance(obj.get("base_resp"), dict):
                    base_resp = obj["base_resp"]
                if isinstance(obj.get("extra_info"), dict):
                    extra_info = obj["extra_info"]
                data = obj.get("data") or {}
                if isinstance(data, dict):
                    if isinstance(data.get("audio"), str):
                        audio_parts.append(data["audio"])
                    if "status" in data:
                        status = data["status"]

        return {
            "data": {"audio": "".join(audio_parts), "status": status},
            "base_resp": base_resp,
            "extra_info": extra_info,
        }

    @staticmethod
    def _minimax_response_error(response: dict[str, Any]) -> str:
        base_resp = response.get("base_resp") or {}
        status_code = base_resp.get("status_code")
        if status_code in (None, 0):
            return ""
        return str(base_resp.get("status_msg") or f"status_code={status_code}")

    async def _download_minimax_audio(self, client: httpx.AsyncClient, audio: Any, audio_format: str) -> Path:
        urls = audio if isinstance(audio, list) else [audio]
        url = next(
            (item for item in urls if isinstance(item, str) and item.startswith(("http://", "https://"))),
            "",
        )
        if not url:
            raise ValueError("MiniMax data.audio did not contain a downloadable URL")
        r = await client.get(url, timeout=180.0)
        r.raise_for_status()
        out_path = self._output_path(audio_format)
        out_path.write_bytes(r.content)
        return out_path

    async def _stream_audio_pcm(self, payload: dict[str, Any]) -> tuple[bytes, str]:
        """Stream a chat-completions audio response → (pcm16 bytes, transcript).

        Concatenates the base64 ``delta.audio.data`` chunks (and any transcript
        text) from the SSE stream. Raises ``httpx.HTTPStatusError`` on non-2xx so
        ``execute`` can format it the same way as the image path.
        """
        pcm = bytearray()
        transcript_parts: list[str] = []
        headers = {
            "Authorization": f"Bearer {self.api_key}",
            "Content-Type": "application/json",
        }
        async with httpx.AsyncClient(proxy=self._proxy, timeout=180.0) as client:
            async with client.stream("POST", f"{self.api_base}/chat/completions", headers=headers, json=payload) as r:
                if r.status_code >= 400:
                    await r.aread()  # load body so .text/raise_for_status carry the error
                    r.raise_for_status()
                async for line in r.aiter_lines():
                    if not line.startswith("data:"):
                        continue
                    data = line[len("data:") :].strip()
                    if data == "[DONE]":
                        break
                    try:
                        obj = json.loads(data)
                    except json.JSONDecodeError:
                        continue
                    delta = (obj.get("choices") or [{}])[0].get("delta") or {}
                    audio = delta.get("audio") or {}
                    if chunk := audio.get("data"):
                        pcm += base64.b64decode(chunk)
                    if t := audio.get("transcript"):
                        transcript_parts.append(t)
        return bytes(pcm), "".join(transcript_parts)

    def _write_wav(self, path: Path, pcm: bytes) -> None:
        """Wrap raw pcm16 bytes into a WAV container (stdlib, no deps)."""
        with wave.open(str(path), "wb") as w:
            w.setnchannels(self._PCM_CHANNELS)
            w.setsampwidth(self._PCM_SAMPWIDTH)
            w.setframerate(self._PCM_RATE)
            w.writeframes(pcm)

    async def _maybe_transcode(self, wav_path: Path, fmt: str) -> tuple[Path, str, str]:
        """Transcode the WAV to ``fmt`` via ffmpeg. Returns (path, format, note).

        wav needs nothing; other formats need ffmpeg and fall back to wav with a
        note when it is missing or the conversion fails.
        """
        if fmt == "wav":
            return wav_path, "wav", ""
        ffmpeg = shutil.which("ffmpeg")
        if not ffmpeg:
            return wav_path, "wav", f"ffmpeg not on PATH; saved as wav instead of {fmt}"
        out = wav_path.with_suffix(f".{fmt}")
        proc = await asyncio.create_subprocess_exec(
            ffmpeg,
            "-y",
            "-i",
            str(wav_path),
            str(out),
            stdout=asyncio.subprocess.DEVNULL,
            stderr=asyncio.subprocess.PIPE,
        )
        _, err = await proc.communicate()
        if proc.returncode != 0 or not out.exists():
            logger.warning("ffmpeg transcode to {} failed: {}", fmt, err.decode("utf-8", "replace")[:200])
            return wav_path, "wav", f"ffmpeg transcode to {fmt} failed; saved as wav"
        wav_path.unlink(missing_ok=True)
        return out, fmt, ""


def _find_video_url(obj: Any) -> str | None:
    """Recursively find the first downloadable video URL / data URI in a response.

    The exact completed-response shape for OpenRouter's /videos endpoint is not
    publicly pinned down, so we search defensively rather than hard-code a path.
    """
    if isinstance(obj, str):
        s = obj
        if s.startswith("data:video") or (
            s.startswith(("http://", "https://"))
            and any(ext in s.lower() for ext in (".mp4", ".webm", ".mov", "video"))
        ):
            return s
        return None
    if isinstance(obj, dict):
        # Prefer obvious keys first.
        for key in ("url", "video_url", "download_url", "video", "output", "result"):
            if key in obj and (found := _find_video_url(obj[key])):
                return found
        for v in obj.values():
            if found := _find_video_url(v):
                return found
        return None
    if isinstance(obj, list):
        for item in obj:
            if found := _find_video_url(item):
                return found
        return None
    return None


def _pick_video_url(status: dict[str, Any]) -> str | None:
    """Choose the downloadable content URL from a completed /videos response.

    OpenRouter's completed shape exposes the rendered video under
    ``signed_urls`` / ``unsigned_urls`` (lists). We prefer those explicitly:
    the job's own ``polling_url`` also lives under ``/videos/`` and would
    otherwise be matched by ``_find_video_url``'s "video" substring heuristic,
    yielding the status JSON instead of the clip. For any other (undocumented)
    provider shape we fall back to a defensive scan that excludes the
    polling/status URL.
    """
    for key in ("signed_urls", "unsigned_urls"):
        urls = status.get(key)
        if isinstance(urls, list) and urls and isinstance(urls[0], str):
            return urls[0]
    scannable = {k: v for k, v in status.items() if k != "polling_url"}
    return _find_video_url(scannable)


class VideoGenerateTool(_OpenRouterMediaTool):
    """Generate a video from a text prompt via Kling on OpenRouter (async)."""

    name = "video_generate"
    default_model = "kwaivgi/kling-v3.0-std"  # Kling v3 Standard
    description = (
        "Generate a short video from a text prompt (async; takes a while). Saves "
        "the video under the workspace and returns its path; forward it with the "
        "`message` tool's `media` field."
    )
    parameters = {
        "type": "object",
        "properties": {
            "prompt": {"type": "string", "description": "Text description of the video"},
            "model": {
                "type": "string",
                "description": "Optional OpenRouter video model override (default kwaivgi/kling-v3.0-std)",
            },
            "params": {
                "type": "object",
                "description": (
                    "Optional extra provider params merged into the request, e.g. "
                    '{"duration": 5, "aspect_ratio": "16:9"} (3-15s; 16:9/9:16/1:1)'
                ),
            },
        },
        "required": ["prompt"],
    }

    _POLL_INTERVAL_S = 6.0
    _POLL_TIMEOUT_S = 600.0
    # Backstop above the 600s polling cap; the poll loop gives up first.
    timeout_seconds = 660.0

    async def execute(
        self,
        prompt: str,
        model: str | None = None,
        params: dict[str, Any] | None = None,
        **kwargs: Any,
    ) -> str:
        if not self.api_key:
            return self._no_key_error()

        model_id = self._model(model)
        body: dict[str, Any] = {"model": model_id, "prompt": prompt}
        if params:
            body.update(params)

        headers = {"Authorization": f"Bearer {self.api_key}", "Content-Type": "application/json"}
        try:
            async with httpx.AsyncClient(proxy=self._proxy, timeout=120.0) as client:
                # 1) submit job
                r = await client.post(f"{self.api_base}/videos", headers=headers, json=body)
                r.raise_for_status()
                job = r.json()
                poll_url = job.get("polling_url") or f"{self.api_base}/videos/{job.get('id')}"

                # 2) poll
                status = await self._poll(client, poll_url, headers)
                state = status.get("status")
                if state != "completed":
                    return json.dumps(
                        {
                            "error": f"video job status={state}",
                            "detail": status.get("error") or status,
                            "model": model_id,
                        },
                        ensure_ascii=False,
                    )

                # 3) locate + download the video
                video_url = _pick_video_url(status)
                if not video_url:
                    return json.dumps(
                        {"error": "completed but no video URL found", "raw": status},
                        ensure_ascii=False,
                    )
                if video_url.startswith("data:"):
                    data = base64.b64decode(video_url.split(",", 1)[1])
                else:
                    # OpenRouter returns "unsigned" content URLs on its own host
                    # that need the same Authorization header as the API. Only
                    # send it to OpenRouter — never leak the key to a third-party
                    # (pre-signed CDN/S3) host.
                    dl_headers = headers if video_url.startswith(self.api_base) else None
                    dl = await client.get(video_url, headers=dl_headers, timeout=180.0)
                    dl.raise_for_status()
                    data = dl.content
        except httpx.HTTPStatusError as e:
            return self._format_http_error(e)
        except Exception as e:
            logger.error("video_generate error: {}", e)
            return json.dumps({"error": str(e)}, ensure_ascii=False)

        path = self._output_path("mp4")
        path.write_bytes(data)
        logger.info("video_generate: {} bytes via {} -> {}", len(data), model_id, path)
        return json.dumps({"success": True, "model": model_id, "path": str(path)}, ensure_ascii=False)

    async def _poll(self, client: httpx.AsyncClient, poll_url: str, headers: dict[str, str]) -> dict[str, Any]:
        """Poll until the job leaves the pending/processing state or times out."""
        waited = 0.0
        while waited < self._POLL_TIMEOUT_S:
            r = await client.get(poll_url, headers=headers)
            r.raise_for_status()
            job = r.json()
            if job.get("status") not in ("pending", "processing", "queued", "in_progress"):
                return job
            await asyncio.sleep(self._POLL_INTERVAL_S)
            waited += self._POLL_INTERVAL_S
        return {"status": "timeout"}
